import { Question } from './types';

export const ALL_QUESTIONS: Question[] = [
  {
    id: "1",
    questionText: "图灵于____年发表论文《计算与智能》,提出图灵测试。",
    options: [
      { label: "A", text: "1940" },
      { label: "B", text: "1950" },
      { label: "C", text: "1960" },
      { label: "D", text: "1970" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "2",
    questionText: "截至目前,人工智能经历了____次低谷。",
    options: [
      { label: "A", text: "一" },
      { label: "B", text: "二" },
      { label: "C", text: "三" },
      { label: "D", text: "四" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "3",
    questionText: "图灵测试要求,超过____的测试者不能确定出被测试者是人还是机器。",
    options: [
      { label: "A", text: "10%" },
      { label: "B", text: "20%" },
      { label: "C", text: "30%" },
      { label: "D", text: "40%" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "4",
    questionText: "以下不属于图灵机组件的是____。",
    options: [
      { label: "A", text: "读写头" },
      { label: "B", text: "控制器" },
      { label: "C", text: "卡带" },
      { label: "D", text: "仿真器" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "5",
    questionText: "下面关于神经元的说法,错误的是____。",
    options: [
      { label: "A", text: "神经元结构上大致都可分成细胞体和神经突两部分" },
      { label: "B", text: "神经突又分树突(Dendrites)和轴突(Axon)两种" },
      { label: "C", text: "树突接受刺激(神经冲动)" },
      { label: "D", text: "轴突接受刺激(神经冲动)" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "6",
    questionText: "“人工智能”这一概念诞生于____会议。",
    options: [
      { label: "A", text: "达特茅斯" },
      { label: "B", text: "华盛顿" },
      { label: "C", text: "索尔维" },
      { label: "D", text: "雅尔塔" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "7",
    questionText: "摩尔定律指出,PC芯片每____个月性能提升一倍。",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "12" },
      { label: "C", text: "16" },
      { label: "D", text: "18" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "8",
    questionText: "专家系统是在第____次AI崛起时出现的。",
    options: [
      { label: "A", text: "一" },
      { label: "B", text: "二" },
      { label: "C", text: "三" },
      { label: "D", text: "四" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "9",
    questionText: "下面不属于人工智能三大学派的是____。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "10",
    questionText: "专家系统属于人工智能____学派的产物。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "A",
  },
   {
    id: "11",
    questionText: "感知机属于人工智能____学派的产物。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "12",
    questionText: "马文·明斯基(Marvin Minsky)和西蒙·派珀特(Seymour Papert)出版的《感知器:计算几何简介》指出, ____层的神经网络无法解决不可线性分割的问题(如异或问题)。",
    options: [
      { label: "A", text: "一" },
      { label: "B", text: "二" },
      { label: "C", text: "三" },
      { label: "D", text: "四" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "13",
    questionText: "下面的四个异或(⊕)计算,正确的是____。",
    options: [
      { label: "A", text: "0 ⊕ 0 = 1" },
      { label: "B", text: "0 ⊕ 1 = 0" },
      { label: "C", text: "1 ⊕ 0 = 0" },
      { label: "D", text: "1 ⊕ 1 = 0" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "14",
    questionText: "“AlphaGo”称霸围棋是第____次AI崛起的典型示例。",
    options: [
      { label: "A", text: "一" },
      { label: "B", text: "二" },
      { label: "C", text: "三" },
      { label: "D", text: "四" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "15",
    questionText: "知识图谱是人工智能____学派的代表性成果。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "16",
    questionText: "深度学习是人工智能____学派的代表性成果。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "17",
    questionText: "人工智能____学派起源于控制论。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "18",
    questionText: "人工智能____学派起源于数理逻辑和逻辑推理。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "19",
    questionText: "人工智能____学派起源于仿生学,特别是人脑模型的研究。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "20",
    questionText: "人工智能____学派主张人工智能应从功能模拟入手。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "21",
    questionText: "人工智能____学派主张人工智能应从结构设计入手。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "22",
    questionText: "人工智能____学派主张利用机器对环境作用后的反馈来实现智能进化。",
    options: [
      { label: "A", text: "符号主义 Symbolism" },
      { label: "B", text: "连接主义 Connectionism" },
      { label: "C", text: "行为主义 Behaviorism" },
      { label: "D", text: "生成主义 Generativism" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "23",
    questionText: "以下四个深度学习模型中,最早被提出的是____。",
    options: [
      { label: "A", text: "ZeilerNet" },
      { label: "B", text: "GoogLeNet" },
      { label: "C", text: "AlexNet" },
      { label: "D", text: "ResNet" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "24",
    questionText: "下面哪个模型在2016年3月与围棋世界冠军李世石进行围棋人机大战并以4比1获胜。",
    options: [
      { label: "A", text: "深蓝" },
      { label: "B", text: "AlexNet" },
      { label: "C", text: "ResNet" },
      { label: "D", text: "AlphaGo" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "25",
    questionText: "以下由 OpenAI 提出的大模型中,参数量在15亿级别的是____。",
    options: [
      { label: "A", text: "GPT-1" },
      { label: "B", text: "GPT-2" },
      { label: "C", text: "GPT-3" },
      { label: "D", text: "ChatGPT" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "26",
    questionText: "以下四个大模型中,最早被提出的是____。",
    options: [
      { label: "A", text: "GPT-2" },
      { label: "B", text: "BERT" },
      { label: "C", text: "Turing-NLP" },
      { label: "D", text: "SWITCH T" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "27",
    questionText: "不属于新一代人工智能提出的“三元空间”结构的是____。",
    options: [
      { label: "A", text: "信息网络" },
      { label: "B", text: "仿生学" },
      { label: "C", text: "人类" },
      { label: "D", text: "物理" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "28",
    questionText: "2017年,国务院印发了《新一代人工智能发展规划》。以下不属于中国新一代人工智能战略布局所需的基础理论是____。",
    options: [
      { label: "A", text: "大数据智能" },
      { label: "B", text: "人机混合智能" },
      { label: "C", text: "初级机器学习" },
      { label: "D", text: "群体智能" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "29",
    questionText: "下面关于大数据智能的层级表示,正确的是____。",
    options: [
      { label: "A", text: "数据->知识->决策" },
      { label: "B", text: "决策->知识->数据" },
      { label: "C", text: "知识->数据->决策" },
      { label: "D", text: "数据->决策->知识" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "30",
    questionText: "我国自____年进入大模型快速发展期。",
    options: [
      { label: "A", text: "2016" },
      { label: "B", text: "2018" },
      { label: "C", text: "2020" },
      { label: "D", text: "2022" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "31",
    questionText: "下面不属于大数据智能流程的是____。",
    options: [
      { label: "A", text: "数据" },
      { label: "B", text: "决策" },
      { label: "C", text: "知识" },
      { label: "D", text: "思想" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "32",
    questionText: "下面不属于国产大模型的是____。",
    options: [
      { label: "A", text: "Moss" },
      { label: "B", text: "WeLM" },
      { label: "C", text: "GLM" },
      { label: "D", text: "Gemma" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "33",
    questionText: "下列的 DeepSeek 模型中,强调推理与思维链的是____。",
    options: [
      { label: "A", text: "DeepSeek-V2" },
      { label: "B", text: "DeepSeek-V3" },
      { label: "C", text: "DeepSeek-R1" },
      { label: "D", text: "以上模型都都不是" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "34",
    questionText: "下列关于 DeepSeek 的说法,错误的是____。",
    options: [
      { label: "A", text: "DeepSeek 是国产大模型" },
      { label: "B", text: "DeepSeek目前主要分为V系列与R系列" },
      { label: "C", text: "DeepSeek 在链式思维和复杂逻辑任务上与 GPT-4、Claude 等相抗衡" },
      { label: "D", text: "DeepSeek 完全闭源" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "35",
    questionText: "在人机混合智能中,不属于人类智能提供的思维是____。",
    options: [
      { label: "A", text: "抽象思维:逻辑与推理" },
      { label: "B", text: "形象思维:想象与创造" },
      { label: "C", text: "直觉思维:灵感与顿悟" },
      { label: "D", text: "幻觉思维:发散与空想" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "36",
    questionText: "在人机混合智能中,不属于机器智能提供的能力是____。",
    options: [
      { label: "A", text: "有限的逻辑与推理能力" },
      { label: "B", text: "神经网络的快速推断能力" },
      { label: "C", text: "多模态感知" },
      { label: "D", text: "情绪与情感" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "37",
    questionText: "在人机混合智能中,不属于人类智能对机器智能提供的指导的是______。",
    options: [
      { label: "A", text: "知识灌输" },
      { label: "B", text: "技能强化" },
      { label: "C", text: "指令引导" },
      { label: "D", text: "协同反馈" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "38",
    questionText: "以下关于群体智能历史起源的说法,错误的是____。",
    options: [
      { label: "A", text: "群体智慧由英国统计学家 Francis Galton 提出" },
      { label: "B", text: "基于群体智慧展现的智能在很多任务中往往超过少数个体" },
      { label: "C", text: "基于群体智慧展现的智能在很多任务中甚至可以超过专家的能力" },
      { label: "D", text: "群体智慧与社会学、认知学无关" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "39",
    questionText: "以下不属于人工智能目前的主要模式的是____。",
    options: [
      { label: "A", text: "数据" },
      { label: "B", text: "操作系统" },
      { label: "C", text: "算法(模型)" },
      { label: "D", text: "算力" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "40",
    questionText: "下面关于基于大模型的智能体社会的说法,错误的是____。",
    options: [
      { label: "A", text: "每个 Agent 都有固定的角色" },
      { label: "B", text: "每个 Agent 都有自己的 LLM 模型" },
      { label: "C", text: "Agent 无需记忆" },
      { label: "D", text: "Agent 间可以相互协作" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "41",
    questionText: "神经系统的基本组成单元是____。",
    options: [
      { label: "A", text: "神经元" },
      { label: "B", text: "细胞" },
      { label: "C", text: "突触" },
      { label: "D", text: "大脑" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "42",
    questionText: "神经元的主要构成包括树突、细胞体和____。",
    options: [
      { label: "A", text: "突触" },
      { label: "B", text: "轴突" },
      { label: "C", text: "细胞核" },
      { label: "D", text: "髓鞘" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "43",
    questionText: "人类大脑中大约有____个神经元。",
    options: [
      { label: "A", text: "100亿" },
      { label: "B", text: "450亿" },
      { label: "C", text: "100万亿" },
      { label: "D", text: "860亿" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "44",
    questionText: "人类大脑中大约有____条神经连接。",
    options: [
      { label: "A", text: "100万亿" },
      { label: "B", text: "1000万亿" },
      { label: "C", text: "860亿" },
      { label: "D", text: "100亿" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "45",
    questionText: "1873年,意大利神经生物学家 Camillo Golgi 发明了____的方法,第一次在显微镜下观察到了神经细胞和神经胶质细胞。",
    options: [
      { label: "A", text: "神经元银染色法" },
      { label: "B", text: "单细胞记录法" },
      { label: "C", text: "电子显微镜观察" },
      { label: "D", text: "荧光标记法" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "46",
    questionText: "1897年,英国科学家 C.S.Sherriton 提出用____来描述一个神经元与另一个神经元之间的接触部位,并认为它的主要作用是让两个神经元进行信息传递,使得思维、推理、联想等复杂的脑机能成为可能。",
    options: [
      { label: "A", text: "轴突" },
      { label: "B", text: "突触" },
      { label: "C", text: "细胞膜" },
      { label: "D", text: "髓鞘" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "47",
    questionText: "大脑最外边有一层颜色较深的褶皱结构,厚度约2~3厘米,面积约2200平方厘米,它是整个大脑神经细胞最集中的区域,被认为是一切智能的来源地,这部分结构被称为____。",
    options: [
      { label: "A", text: "白质" },
      { label: "B", text: "灰质" },
      { label: "C", text: "脑膜" },
      { label: "D", text: "脑脊液" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "48",
    questionText: "____在大脑皮层的下面,是神经细胞的轴突所在,它将大脑的不同区域以及大脑和脊髓等其他神经系统部分连接起来,就像是大脑的“通信网络”。",
    options: [
      { label: "A", text: "白质" },
      { label: "B", text: "灰质" },
      { label: "C", text: "脑膜" },
      { label: "D", text: "脑脊液" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "49",
    questionText: "____充满在脑室系统、蛛网膜下腔和脊髓中央管内,在大脑和脊髓周围形成了一个液体缓冲层,就像一个柔软的“垫子”,能够减轻头部受到外伤时对脑和脊髓的冲击力。同时也为脑组织提供营养物质,带走代谢废物。",
    options: [
      { label: "A", text: "白质" },
      { label: "B", text: "灰质" },
      { label: "C", text: "脑膜" },
      { label: "D", text: "脑脊液" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "50",
    questionText: "大脑的解剖结构可以分为“三沟五叶”。五叶指额叶、顶叶、颞叶、枕叶及岛叶。其中,大脑的视觉皮层位于____,是大脑皮层中处理视觉信息的关键区域。",
    options: [
      { label: "A", text: "额叶" },
      { label: "B", text: "顶叶" },
      { label: "C", text: "颞叶" },
      { label: "D", text: "枕叶" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "51",
    questionText: "大脑的解剖结构可以分为“三沟五叶”,这里面的五叶指额叶、顶叶、颞叶、枕叶及岛叶。其中,与听觉功能相关的脑区主要位于____。",
    options: [
      { label: "A", text: "额叶" },
      { label: "B", text: "顶叶" },
      { label: "C", text: "颞叶" },
      { label: "D", text: "枕叶" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "52",
    questionText: "源自眼睛的视觉输入经过丘脑的外侧膝状核,首先传递至大脑的初级视觉皮层(primary visual cortex)。初级视觉皮层又称V1区,位于____。",
    options: [
      { label: "A", text: "额叶" },
      { label: "B", text: "顶叶" },
      { label: "C", text: "颞叶" },
      { label: "D", text: "枕叶" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "53",
    questionText: "20世纪50年代,大卫·休伯尔(David Hubel)和托斯坦· Wiesel研究发现,猫的视觉皮层中的简单细胞和复杂细胞通过卷积和下采样的方式对视觉信息进行____处理。其中,简单细胞首先对基本的视觉特征进行提取,然后复杂细胞对简单细胞提供的局部信息进行整合,形成更为抽象和高级的视觉表示。这一视觉系统的信息加工方式在上世纪80年代初被日本科学家福岛邦彦借鉴设计了神经网络模型 Neocognitron,是现代 CNN 的雏形。",
    options: [
      { label: "A", text: "集中" },
      { label: "B", text: "分层" },
      { label: "C", text: "分布式" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "54",
    questionText: "视觉信息在传递到大脑初级视觉皮层之后,开始被两条独立的视觉通路分别进行处理:其中一条被称为____,也叫“what”通路,主要负责物体内容的感知和识别。",
    options: [
      { label: "A", text: "背侧视觉通路" },
      { label: "B", text: "腹侧视觉通路" },
      { label: "C", text: "旁侧视觉通路" },
      { label: "D", text: "内侧视觉通路" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "55",
    questionText: "视觉信息在传递到大脑初级视觉皮层之后,开始被两条独立的视觉通路分别进行处理:其中一条被称为____,也叫“where”通路,主要负责物体空间位置的感知和识别。",
    options: [
      { label: "A", text: "背侧视觉通路" },
      { label: "B", text: "腹侧视觉通路" },
      { label: "C", text: "旁侧视觉通路" },
      { label: "D", text: "内侧视觉通路" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "56",
    questionText: "在人的大脑中存在着多个专门加工某一特定类别物体的脑区,这一现象被称为物体识别的____加工理论。",
    options: [
      { label: "A", text: "特异性" },
      { label: "B", text: "整体性" },
      { label: "C", text: "分布式" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "57",
    questionText: "从初级听觉皮层出发,大脑可分离出两条主要的独立传导路径进行声音的感知和识别。其中,腹侧听觉通路,又称“what”通路,主要负责声音____的识别。",
    options: [
      { label: "A", text: "内容" },
      { label: "B", text: "方向" },
      { label: "C", text: "大小" },
      { label: "D", text: "频率" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "58",
    questionText: "从初级听觉皮层出发,大脑可分离出两条主要的独立传导路径进行声音的感知和识别。其中,听觉背侧通路,又称“where”通路,其主要功能是声音的____。",
    options: [
      { label: "A", text: "内容识别" },
      { label: "B", text: "定位" },
      { label: "C", text: "大小识别" },
      { label: "D", text: "频率识别" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "59",
    questionText: "我们大脑中与语言功能相关的脑区主要位于____。",
    options: [
      { label: "A", text: "左半球大脑" },
      { label: "B", text: "右半球大脑" },
      { label: "C", text: "两侧大脑且均匀分布" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "60",
    questionText: "大脑中有两个重要的脑区与语言的认知活动关系密切,分别是 Broca 脑区和Wernicke 脑区,其中,Broca 脑区在____加工中起重要作用。",
    options: [
      { label: "A", text: "语法" },
      { label: "B", text: "声音" },
      { label: "C", text: "音频" },
      { label: "D", text: "语义" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "61",
    questionText: "大脑中有两个重要的脑区与语言的认知活动关系密切,分别是 Broca 脑区和Wernicke 脑区,其中,Wernicke 脑区在____中起重要作用。",
    options: [
      { label: "A", text: "语法加工" },
      { label: "B", text: "声音识别" },
      { label: "C", text: "音频辨识" },
      { label: "D", text: "语义理解" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "62",
    questionText: "根据信息维持时间的长短,记忆可以分为三种类型:感觉记忆、短时记忆和长时记忆。其中,____是指信息在几秒到几分钟内保持的记忆,通常需要不断的复述才能维持。",
    options: [
      { label: "A", text: "感觉记忆" },
      { label: "B", text: "短时记忆" },
      { label: "C", text: "长时记忆" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "63",
    questionText: "按照信息维持时间的长短,记忆可以分为三种类型:感觉记忆、短时记忆和长时记忆。其中,____是指信息可以保持几天到数十年的记忆,是记忆系统中容量最大且最持久的部分。",
    options: [
      { label: "A", text: "感觉记忆" },
      { label: "B", text: "短时记忆" },
      { label: "C", text: "长时记忆" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "64",
    questionText: "大脑中有一个区域在记忆形成中起到了非常关键的作用,该区域位于____。",
    options: [
      { label: "A", text: "海马体" },
      { label: "B", text: "杏仁核" },
      { label: "C", text: "前额叶" },
      { label: "D", text: "小脑" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "65",
    questionText: "情绪是人脑的一种基本认知功能。从心理学的角度来看,情绪是一种复杂的体验,包含主观体验,生理反应,行为表现三个部分。其中,____是指个体在情绪体验期间通过面部表情、肢体姿势和具体动作等方式所展现的外部行为。通过观察个体的____,我们可以推断其情绪状态,从而更好地理解和评估情绪的全面影响。",
    options: [
      { label: "A", text: "主观体验" },
      { label: "B", text: "生理反应" },
      { label: "C", text: "行为表现" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "66",
    questionText: "认知神经科学研究发现,大脑中有多个脑区负责情绪和情感认知。大脑边缘系统中的____是其中最重要的脑区,主要负责感知和产生情绪,尤其是恐惧情绪。",
    options: [
      { label: "A", text: "海马体" },
      { label: "B", text: "杏仁核" },
      { label: "C", text: "扣带回" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "67",
    questionText: "通过获取并分析大脑的神经活动信号,从而获取特定心理状态、感官或行为信息的过程被称为____。",
    options: [
      { label: "A", text: "脑编码" },
      { label: "B", text: "脑解码" },
      { label: "C", text: "脑重塑" },
      { label: "D", text: "脑可视化" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "68",
    questionText: "通过借鉴或模仿大脑的结构和功能,从而开发出具有大脑智能或认知能力的计算系统或技术被称为____。",
    options: [
      { label: "A", text: "脑编码" },
      { label: "B", text: "脑解码" },
      { label: "C", text: "类脑计算" },
      { label: "D", text: "脑重塑" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "69",
    questionText: "在大脑和外部设备间建立通信和控制的技术被称为____技术。",
    options: [
      { label: "A", text: "脑编码" },
      { label: "B", text: "脑解码" },
      { label: "C", text: "脑机接口" },
      { label: "D", text: "脑重塑" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "70",
    questionText: "受____的启发,神经科学家麦卡洛克(Warren McCulloch)和数学家皮茨(Walter Pitts)在1943年合作提出了以他们名字首字母命名的“M-P”模型,这是现代人工神经网络的基础。",
    options: [
      { label: "A", text: "神经元细胞结构特性及信息传递方式" },
      { label: "B", text: "大脑视觉系统层次性加工方式" },
      { label: "C", text: "大脑视觉系统双通路理论" },
      { label: "D", text: "神经突触连接理论" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "71",
    questionText: "1957年,美国心理学家弗兰克·罗森布拉特(Frank Rosenblat)提出了____,在一定程度上模拟了人类的思维过程,是第一个具有学习能力的算法模型。",
    options: [
      { label: "A", text: "感知机" },
      { label: "B", text: "Neocognitron" },
      { label: "C", text: "CNN" },
      { label: "D", text: "Hebb 学习规则" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "72",
    questionText: "1980年,日本科学家福岛邦彦首次将视觉感受野以及视觉皮层分层加工方式的概念引入人工神经网络,设计出了神经网络模型____,它被认为是卷积神经网络的雏形。",
    options: [
      { label: "A", text: "CNN" },
      { label: "B", text: "Neocognitron" },
      { label: "C", text: "感知机" },
      { label: "D", text: "Hebb 学习规则" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "73",
    questionText: "1989年,杨立昆(Yann LeCun)将杰弗里·辛顿(Geoffrey Hinton)提出的____算法引入到卷积神经网络的优化中,开发出了LeNet,被认为是最早用于实际应用的卷积神经网络模型。",
    options: [
      { label: "A", text: "Hebb学习" },
      { label: "B", text: "反向传播算法" },
      { label: "C", text: "梯度下降" },
      { label: "D", text: "最小二乘优化" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "74",
    questionText: "2012年,以____为核心算法开发的AlexNet在大规模视觉识别挑战赛(ILSVRC)中以领先第二名10.8个百分点的优势一举夺得比赛冠军,开启了以深度神经网络为代表的人工智能技术在计算机视觉领域应用的浪潮。",
    options: [
      { label: "A", text: "Hebb学习" },
      { label: "B", text: "神经网络" },
      { label: "C", text: "CNN" },
      { label: "D", text: "Transformer" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "75",
    questionText: "1982年,美国物理学家约翰-霍普菲尔德(John Hopfield)设计出了具有存储和记忆功能的Hopfield神经网络。2024年,约翰-霍普菲尔德和杰夫.辛顿(Geoffrey Hinton)共同获得诺贝尔____奖,以表彰他们“基于人工神经网络实现机器学习的基础性发现和发明”。",
    options: [
      { label: "A", text: "化学" },
      { label: "B", text: "物理学" },
      { label: "C", text: "生理或医学" },
      { label: "D", text: "经济学" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "76",
    questionText: "1997年,Sepp Hochreiter (霍克赖特)和施密德胡贝尔(Schmidhuber)提出了____,通过引入复杂的门控机制,能够有效控制信息流动,记住长期的依赖信息,忘记无关的细节信息,从而有效缓解模型训练中梯度消失和爆炸的问题。",
    options: [
      { label: "A", text: "长短期记忆网络(Long Short-Term Memory, LSTM)" },
      { label: "B", text: "循环神经网络(Recurrent Neural Network, RNN )" },
      { label: "C", text: "卷积神经网络(Convolutional Neural Networks, CNN )" },
      { label: "D", text: "Hopfield 神经网络" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "77",
    questionText: "2017 年,Google 研究团队提出了以____为核心算法的 Transformer。Transformer 对数据的处理方式类似于大脑在处理信息时的聚焦行为,能够使模型更加关注输入序列中的关键部分,更好地处理长序列数据中的复杂语义关系,从而提高模型的处理效率和准确性。",
    options: [
      { label: "A", text: "自注意力机制" },
      { label: "B", text: "卷积" },
      { label: "C", text: "反向传播" },
      { label: "D", text: "控制门" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "78",
    questionText: "谷歌 DeepMind 团队开发的AlphaGo 系列,利用了深度神经网络强大的特征提取能力和____的决策能力,使得智能体能够在复杂的环境中学习到更加高效的行为策略,在围棋领域取得了重大突破,击败了人类顶尖棋手。",
    options: [
      { label: "A", text: "Transformer" },
      { label: "B", text: "强化学习" },
      { label: "C", text: "迁移学习" },
      { label: "D", text: "联邦学习" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "79",
    questionText: "上世纪六七十年代,为应对第一次人工智能研究低潮,英国著名科学家克里斯托弗-朗盖特-希金斯(Christopher Longuet-Higgins)提出人工智能的发展可以从研究数学、语言、心理、生理等与人类思维和感知直接相关的科学领域入手,由此而产生了一门新的学科____。",
    options: [
      { label: "A", text: "认知神经科学" },
      { label: "B", text: "认知科学" },
      { label: "C", text: "行为学" },
      { label: "D", text: "认知心理学" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "80",
    questionText: "认为智能是通过感知与行为的交互体现的,更强调智能体对外界环境的自适应能力的学派是____学派。",
    options: [
      { label: "A", text: "符号主义" },
      { label: "B", text: "行为主义" },
      { label: "C", text: "连接主义" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "81",
    questionText: "机器学习最早由哪位科学家提出其经典定义?",
    options: [
      { label: "A", text: "汤姆·米切尔(Tom Mitchell)" },
      { label: "B", text: "亚瑟·塞缪尔(Arthur Samuel)" },
      { label: "C", text: "艾伦·图灵(Alan Turing)" },
      { label: "D", text: "杰弗里·辛顿(Geoffrey Hinton )" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "82",
    questionText: "根据汤姆·米切尔(Tom Mitchell)的形式化定义,机器学习的核心标准是?",
    options: [
      { label: "A", text: "模型必须使用神经网络" },
      { label: "B", text: "程序通过经验提升任务性能" },
      { label: "C", text: "必须处理高维复杂数据" },
      { label: "D", text: "需要人工标注所有训练样本" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "83",
    questionText: "以下哪种场景属于无监督学习的典型应用?",
    options: [
      { label: "A", text: "根据历史销售数据预测房价" },
      { label: "B", text: "对客户购买行为进行聚类分群" },
      { label: "C", text: "识别医学影像中的肿瘤区域" },
      { label: "D", text: "训练机器人通过试错学习行走" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "84",
    questionText: "关于机器学习与人工智能的关系,以下说法错误的是?",
    options: [
      { label: "A", text: "机器学习是实现人工智能的核心技术之一" },
      { label: "B", text: "深度学习是机器学习的子领域" },
      { label: "C", text: "强化学习与监督学习完全独立,无任何关联" },
      { label: "D", text: "机器学习模型可适应动态环境的变化" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "85",
    questionText: "以下哪一项是机器学习的核心要素之一?",
    options: [
      { label: "A", text: "用户界面设计" },
      { label: "B", text: "数据清洗工具" },
      { label: "C", text: "目标函数" },
      { label: "D", text: "编程语言选择" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "86",
    questionText: "均方误差(MSE)主要用于评估以下哪个要素的表现?",
    options: [
      { label: "A", text: "数据质量" },
      { label: "B", text: "模型复杂度" },
      { label: "C", text: "目标函数误差" },
      { label: "D", text: "优化算法效率" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "87",
    questionText: "当模型包含成千上万个参数时,为什么通常不直接求导找最优解?",
    options: [
      { label: "A", text: "目标函数不存在极小值" },
      { label: "B", text: "均方误差不适用于高维数据" },
      { label: "C", text: "计算复杂度过高或缺乏解析解" },
      { label: "D", text: "数据量不足以支持参数优化" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "88",
    questionText: "关于梯度下降算法的描述,哪一项错误?",
    options: [
      { label: "A", text: "沿梯度反方向调整参数以减小损失" },
      { label: "B", text: "适用于深度学习模型的参数优化" },
      { label: "C", text: "需计算目标函数对参数的偏导数" },
      { label: "D", text: "仅能用于线性模型的参数求解" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "89",
    questionText: "机器学习工作流程的第一步是?",
    options: [
      { label: "A", text: "模型训练" },
      { label: "B", text: "数据准备" },
      { label: "C", text: "模型部署" },
      { label: "D", text: "超参数调优" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "90",
    questionText: "验证集的主要作用是什么?",
    options: [
      { label: "A", text: "最终评估模型性能" },
      { label: "B", text: "调整模型超参数" },
      { label: "C", text: "增加训练数据量" },
      { label: "D", text: "替换测试集" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "91",
    questionText: "过拟合的典型表现是?",
    options: [
      { label: "A", text: "训练集和测试集误差均高" },
      { label: "B", text: "训练集误差低,测试集误差高" },
      { label: "C", text: "训练集误差高,测试集误差低" },
      { label: "D", text: "训练集和测试集误差均低" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "92",
    questionText: "以下哪种情况会因数据分布不一致导致模型失效?",
    options: [
      { label: "A", text: "训练集与测试集均包含猫的正面和侧面图像" },
      { label: "B", text: "训练集仅含白天照片,测试集仅含夜间照片" },
      { label: "C", text: "训练集和测试集均经过相同归一化处理" },
      { label: "D", text: "所有数据集均来自同一医疗影像设备" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "93",
    questionText: "以下哪项措施无法直接解决欠拟合?",
    options: [
      { label: "A", text: "增加神经网络的隐藏层数" },
      { label: "B", text: "引入数据增强技术扩充训练集" },
      { label: "C", text: "使用 L2 正则化约束模型参数" },
      { label: "D", text: "添加更多与任务相关的特征" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "94",
    questionText: "模型部署后需定期重新训练的主要原因是什么?",
    options: [
      { label: "A", text: "确保模型在训练集上达到100%准确率" },
      { label: "B", text: "适应数据分布随时间推移发生的变化" },
      { label: "C", text: "验证集已完全替代测试集的功能" },
      { label: "D", text: "减少模型推理时的计算资源消耗" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "95",
    questionText: "以下哪种任务属于监督学习的典型应用?",
    options: [
      { label: "A", text: "根据用户购买行为进行客户聚类分群" },
      { label: "B", text: "根据已有标注数据训练气温预测模型" },
      { label: "C", text: "对新闻评论进行情感极性聚类" },
      { label: "D", text: "对于已有数据进行降维处理" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "96",
    questionText: "弱监督学习最可能用于以下哪种场景?",
    options: [
      { label: "A", text: "拥有10万张精确标注的医学影像" },
      { label: "B", text: "只有图片是否包含动物的二值标签" },
      { label: "C", text: "所有数据均通过传感器自动生成标签" },
      { label: "D", text: "需要实时与虚拟环境交互的机器人" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "97",
    questionText: "监督学习与非监督学习的根本区别在于?",
    options: [
      { label: "A", text: "是否使用神经网络结构" },
      { label: "B", text: "是否需要定义目标函数" },
      { label: "C", text: "是否依赖标注数据训练" },
      { label: "D", text: "是否处理高维数据特征" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "98",
    questionText: "“回归”一词的提出与以下哪位科学家直接相关?",
    options: [
      { label: "A", text: "亚瑟·塞缪尔(Arthur Samuel )" },
      { label: "B", text: "弗朗西斯·高尔顿(Francis Galton )" },
      { label: "C", text: "汤姆·米切尔(Tom Mitchell )" },
      { label: "D", text: "杰弗里·辛顿(Geoffrey Hinton )" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "99",
    questionText: "批量梯度下降(BGD)与随机梯度下降(SGD)的核心区别是?",
    options: [
      { label: "A", text: "BGD 使用全部样本更新参数,SGD使用单个样本" },
      { label: "B", text: "BGD 需要计算偏导数,SGD 直接随机调整参数" },
      { label: "C", text: "BGD 仅用于线性回归,SGD 适用于所有模型" },
      { label: "D", text: "BGD 必须设置学习率,SGD 无需学习率" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "100",
    questionText: "逻辑回归主要用于解决以下哪种任务?",
    options: [
      { label: "A", text: "回归分析" },
      { label: "B", text: "二分类" },
      { label: "C", text: "多分类" },
      { label: "D", text: "聚类" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "101",
    questionText: "在逻辑回归中,Sigmoid 函数的主要作用是什么?",
    options: [
      { label: "A", text: "计算特征权重" },
      { label: "B", text: "将线性输出转换为概率值" },
      { label: "C", text: "定义损失函数" },
      { label: "D", text: "优化学习率" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "102",
    questionText: "K均值算法的正确步骤顺序是?",
    options: [
      { label: "A", text: "分配样本 → 初始化中心 → 更新中心 → 迭代" },
      { label: "B", text: "初始化中心 → 更新中心 → 分配样本 → 迭代" },
      { label: "C", text: "初始化中心 → 分配样本 → 更新中心 → 迭代" },
      { label: "D", text: "分配样本 → 更新中心 → 初始化中心 → 迭代" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "103",
    questionText: "K均值算法的目标是最小化以下哪项?",
    options: [
      { label: "A", text: "簇间距离之和" },
      { label: "B", text: "簇内距离平方和" },
      { label: "C", text: "全局方差" },
      { label: "D", text: "分类准确率" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "104",
    questionText: "经验误差反映的是模型在哪个数据集上的表现?",
    options: [
      { label: "A", text: "训练集" },
      { label: "B", text: "测试集" },
      { label: "C", text: "验证集" },
      { label: "D", text: "新采集的实时数据" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "105",
    questionText: "过拟合的模型最可能表现出以下哪种特征?",
    options: [
      { label: "A", text: "训练集误差高,测试集误差高" },
      { label: "B", text: "训练集误差低,测试集误差高" },
      { label: "C", text: "训练集误差高,测试集误差低" },
      { label: "D", text: "训练集误差低,测试集误差低" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "106",
    questionText: "k折交叉验证的核心优势是什么?",
    options: [
      { label: "A", text: "计算速度最快" },
      { label: "B", text: "减少数据划分的随机性影响" },
      { label: "C", text: "完全避免模型过拟合" },
      { label: "D", text: "适用于超大数据集" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "107",
    questionText: "关于留出法与交叉验证的对比,以下描述错误的是?",
    options: [
      { label: "A", text: "留出法的数据利用率低于交叉验证" },
      { label: "B", text: "交叉验证的稳定性通常高于留出法" },
      { label: "C", text: "留出法更适合需要快速验证的大数据集" },
      { label: "D", text: "交叉验证通过单次划分即可完成评估" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "108",
    questionText: "在机器学习模型评估中,混淆矩阵中的“False Negative(FN)”表示什么?",
    options: [
      { label: "A", text: "模型正确预测为正类的样本数" },
      { label: "B", text: "模型正确预测为负类的样本数" },
      { label: "C", text: "模型将负类错误预测为正类的样本数" },
      { label: "D", text: "模型将正类错误预测为负类的样本数" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "109",
    questionText: "在医疗癌症筛查任务中,优先保证高召回率的目的是?",
    options: [
      { label: "A", text: "减少健康人被误诊为癌症的概率" },
      { label: "B", text: "避免漏诊真正的癌症患者" },
      { label: "C", text: "降低检测设备的成本" },
      { label: "D", text: "提高诊断报告的书写效率" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "110",
    questionText: "关于F1 分数的描述,以下哪项错误?",
    options: [
      { label: "A", text: "是精确率和召回率的调和平均数" },
      { label: "B", text: "取值范围在0到1之间" },
      { label: "C", text: "当精确率与召回率相等时,F1 分数等于它们" },
      { label: "D", text: "对类别分布不平衡的数据集无参考价值" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "111",
    questionText: "奥卡姆剃刀原则在机器学习中的核心建议是?",
    options: [
      { label: "A", text: "选择预测准确率最高的模型" },
      { label: "B", text: "在满足需求时优先选择更简单的模型" },
      { label: "C", text: "始终使用深度学习模型以应对复杂任务" },
      { label: "D", text: "根据硬件成本选择计算资源消耗低的模型" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "112",
    questionText: "以下哪种方法不能直接用于缓解过拟合?",
    options: [
      { label: "A", text: "增加训练数据量" },
      { label: "B", text: "为模型添加 L2 正则化项" },
      { label: "C", text: "使用交叉验证评估模型" },
      { label: "D", text: "采用更复杂的神经网络结构" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "113",
    questionText: "选择机器学习模型时,应考虑的主要因素不包括?",
    options: [
      { label: "A", text: "任务类型(如分类或回归)" },
      { label: "B", text: "数据噪声水平与标签质量" },
      { label: "C", text: "模型训练所需的编程语言" },
      { label: "D", text: "任务对精确率或召回率的侧重" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "114",
    questionText: "关于L2 正则化的作用,以下描述正确的是?",
    options: [
      { label: "A", text: "通过增大模型参数绝对值来提升拟合能力" },
      { label: "B", text: "通过限制参数大小来降低模型复杂度" },
      { label: "C", text: "直接删除不重要的特征以简化模型" },
      { label: "D", text: "仅适用于线性回归任务" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "115",
    questionText: "对于简单数据集线性可分的二分类任务,以下哪种模型最符合奥卡姆剃刀原则?",
    options: [
      { label: "A", text: "深度神经网络(100层)" },
      { label: "B", text: "线性分类器" },
      { label: "C", text: "复杂非线性分类器" },
      { label: "D", text: "卷积神经网络(ResNet 架构)" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "116",
    questionText: "机器学习的核心目标是让模型具备什么能力?",
    options: [
      { label: "A", text: "在训练数据上达到 100%准确率" },
      { label: "B", text: "对未知数据做出准确预测(泛化能力)" },
      { label: "C", text: "快速处理高维度数据" },
      { label: "D", text: "完全复现人类的学习过程" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "117",
    questionText: "机器学习中强调“训练集、验证集、测试集数据分布一致”主要是为了?",
    options: [
      { label: "A", text: "降低数据存储成本" },
      { label: "B", text: "确保模型学到可泛化的规律" },
      { label: "C", text: "简化模型训练流程" },
      { label: "D", text: "提高算法计算速度" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "118",
    questionText: "以下哪项是机器学习与传统编程的主要区别?",
    options: [
      { label: "A", text: "机器学习必须使用 Python 语言" },
      { label: "B", text: "机器学习通过数据自动生成规则,而非人工编写规则" },
      { label: "C", text: "机器学习不需要任何数学知识" },
      { label: "D", text: "传统编程无法处理结构化数据" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "119",
    questionText: "以下哪种描述最能概括“监督学习”的特点?",
    options: [
      { label: "A", text: "通过试错与环境交互学习" },
      { label: "B", text: "从无标签数据中发现隐藏模式" },
      { label: "C", text: "根据已知答案调整预测规则" },
      { label: "D", text: "仅用于处理图像和语音数据" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "120",
    questionText: "为什么说“数据是机器学习的基础”?",
    options: [
      { label: "A", text: "数据量越大模型准确率必然越高" },
      { label: "B", text: "模型通过分析数据规律而非预设规则学习" },
      { label: "C", text: "所有数据必须由人工手动标注" },
      { label: "D", text: "数据决定了计算机硬件的选择" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "121",
    questionText: "模型“泛化能力”差通常意味着?",
    options: [
      { label: "A", text: "训练速度过慢" },
      { label: "B", text: "在新数据上预测效果不佳" },
      { label: "C", text: "无法处理高维度特征" },
      { label: "D", text: "需要更多计算内存" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "122",
    questionText: "在医疗诊断任务中使用机器学习模型时,以下哪项是最需要关注的伦理问题?",
    options: [
      { label: "A", text: "模型是否采用最新深度学习算法" },
      { label: "B", text: "预测结果的可解释性与错误风险" },
      { label: "C", text: "训练数据是否包含足够多的类别标签" },
      { label: "D", text: "模型能否在 GPU 上加速运算" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "123",
    questionText: "若线性回归的均方误差函数对参数w的偏导数为正,应如何调整 w?",
    options: [
      { label: "A", text: "增大 w以减小误差" },
      { label: "B", text: "减小 w 以减小误差" },
      { label: "C", text: "保持w不变" },
      { label: "D", text: "随机改变 w方向" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "124",
    questionText: "深度学习的核心思想是模拟以下哪种结构?",
    options: [
      { label: "A", text: "量子计算机" },
      { label: "B", text: "大脑神经网络" },
      { label: "C", text: "传统数据库" },
      { label: "D", text: "遗传算法" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "125",
    questionText: "人工神经网络的训练本质是调整什么?",
    options: [
      { label: "A", text: "输入数据" },
      { label: "B", text: "激活函数类型" },
      { label: "C", text: "神经元连接权重" },
      { label: "D", text: "网络层数" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "126",
    questionText: "下列哪项是人工神经网络与生物神经网络的共同点?",
    options: [
      { label: "A", text: "依赖电子信号传递" },
      { label: "B", text: "神经元连接强度可调" },
      { label: "C", text: "完全模拟大脑结构" },
      { label: "D", text: "无需学习过程" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "127",
    questionText: "单层感知机无法解决以下哪种问题?",
    options: [
      { label: "A", text: "与门(AND)" },
      { label: "B", text: "或门(OR)" },
      { label: "C", text: "异或门(XOR)" },
      { label: "D", text: "非门(NOT)" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "128",
    questionText: "单层感知机可以实现的分类任务是?",
    options: [
      { label: "A", text: "线性可分问题" },
      { label: "B", text: "非线性可分问题" },
      { label: "C", text: "图像生成" },
      { label: "D", text: "语音识别" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "129",
    questionText: "下列哪项是多层感知机解决异或(XOR)问题的关键?",
    options: [
      { label: "A", text: "增加输入维度" },
      { label: "B", text: "引入隐藏层" },
      { label: "C", text: "使用阶跃函数" },
      { label: "D", text: "减少训练数据" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "130",
    questionText: "以下哪项是BP算法的局限性?",
    options: [
      { label: "A", text: "只能处理线性问题" },
      { label: "B", text: "梯度消失问题" },
      { label: "C", text: "不需要训练数据" },
      { label: "D", text: "只能用于单层网络" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "131",
    questionText: "反向传播(BP)算法的核心思想基于什么数学原理?",
    options: [
      { label: "A", text: "傅里叶变换" },
      { label: "B", text: "链式法则" },
      { label: "C", text: "欧拉定理" },
      { label: "D", text: "拉格朗日乘数" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "132",
    questionText: "以下哪项不是传统神经网络的局限性?",
    options: [
      { label: "A", text: "过拟合" },
      { label: "B", text: "计算复杂度低" },
      { label: "C", text: "局部极值问题" },
      { label: "D", text: "梯度消失" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "133",
    questionText: "以下哪项是 BP 算法更新权重的依据?",
    options: [
      { label: "A", text: "输入数据分布" },
      { label: "B", text: "误差梯度" },
      { label: "C", text: "网络层数" },
      { label: "D", text: "激活函数类型" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "134",
    questionText: "下列哪项属于BP算法的计算缺点?",
    options: [
      { label: "A", text: "训练速度极快" },
      { label: "B", text: "参数数量随网络规模指数增长" },
      { label: "C", text: "仅需单次迭代" },
      { label: "D", text: "无过拟合风险" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "135",
    questionText: "当 MP 模型采用阈值(阶跃)函数作为激活函数时,神经元可以看作是什么?",
    options: [
      { label: "A", text: "非线性分类器" },
      { label: "B", text: "线性回归模型" },
      { label: "C", text: "线性分类器" },
      { label: "D", text: "聚类模型" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "136",
    questionText: "通用/万能近似定理表明神经网络可以用来逼近什么函数?( )",
    options: [
      { label: "A", text: "任意函数" },
      { label: "B", text: "任意连续函数" },
      { label: "C", text: "线性函数" },
      { label: "D", text: "非线性函数" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "137",
    questionText: "BP算法的核心思想是在什么学习基础上进行多层扩展? ( )",
    options: [
      { label: "A", text: "Hebb 学习" },
      { label: "B", text: "δ学习" },
      { label: "C", text: "强化学习" },
      { label: "D", text: "无监督学习" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "138",
    questionText: "BP算法中,通过什么法则计算误差函数对每一层权重的梯度? ( )",
    options: [
      { label: "A", text: "乘法法则" },
      { label: "B", text: "链式法则" },
      { label: "C", text: "加法法则" },
      { label: "D", text: "除法法则" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "139",
    questionText: "BP算法的算法流程不包括以下哪一步? ( )",
    options: [
      { label: "A", text: "正向传播预测输出" },
      { label: "B", text: "计算输出误差" },
      { label: "C", text: "Hebb 法则更新权重" },
      { label: "D", text: "梯度下降算法更新权重" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "140",
    questionText: "BP算法中,常用的误差计算方法是什么? ( )",
    options: [
      { label: "A", text: "绝对误差" },
      { label: "B", text: "均方误差" },
      { label: "C", text: "交叉熵误差" },
      { label: "D", text: "对数误差" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "141",
    questionText: "当神经网络结构复杂且训练数据有限时,容易出现什么问题? ( )",
    options: [
      { label: "A", text: "梯度消失" },
      { label: "B", text: "梯度爆炸" },
      { label: "C", text: "过拟合" },
      { label: "D", text: "欠拟合" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "142",
    questionText: "随着隐含层增加,反向传播传递给较低层的信息会减少,这会导致什么问题?( )",
    options: [
      { label: "A", text: "梯度消失" },
      { label: "B", text: "局部极值" },
      { label: "C", text: "计算复杂度降低" },
      { label: "D", text: "过拟合" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "143",
    questionText: "证明了多层神经网络可以通过反向传播算法有效训练,解决单层感知机局限性的是哪种算法? ( )",
    options: [
      { label: "A", text: "Hebb 算法" },
      { label: "B", text: "δ算法" },
      { label: "C", text: "BP算法" },
      { label: "D", text: "梯度下降算法" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "144",
    questionText: "卷积神经网络(CNN)在处理图像数据时,相较于全连接感知器网络的主要优势是什么?",
    options: [
      { label: "A", text: "参数数量更多" },
      { label: "B", text: "计算复杂度更高" },
      { label: "C", text: "局部连接和参数共享减少参数量" },
      { label: "D", text: "只能处理线性可分问题" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "145",
    questionText: "生物视觉系统中的“简单细胞”对什么信息敏感?",
    options: [
      { label: "A", text: "颜色变化" },
      { label: "B", text: "运动轨迹" },
      { label: "C", text: "复杂纹理" },
      { label: "D", text: "某一朝向的边缘信息" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "146",
    questionText: "现代卷积神经网络的雏形是以下哪个模型?",
    options: [
      { label: "A", text: "AlexNet" },
      { label: "B", text: "LeNet-5" },
      { label: "C", text: "ResNet" },
      { label: "D", text: "Transformer" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "147",
    questionText: "卷积神经网络中,池化层的主要作用是什么?",
    options: [
      { label: "A", text: "增加特征图的维度" },
      { label: "B", text: "引入非线性激活函数" },
      { label: "C", text: "降低特征图的空间维度并保留重要信息" },
      { label: "D", text: "直接生成分类结果" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "148",
    questionText: "ResNet 的核心创新是引入了什么结构来解决梯度消失问题?",
    options: [
      { label: "A", text: "跳跃连接(Skip Connections )" },
      { label: "B", text: "池化层" },
      { label: "C", text: "全连接层" },
      { label: "D", text: "更大的卷积核" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "149",
    questionText: "以下哪项是 CNN的局限性?",
    options: [
      { label: "A", text: "无法处理图像数据" },
      { label: "B", text: "难以有效捕捉时间序列中的长期依赖关系" },
      { label: "C", text: "参数量过少" },
      { label: "D", text: "只能用于自然语言处理" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "150",
    questionText: "循环神经网络(RNN)的核心特点是什么?",
    options: [
      { label: "A", text: "独立处理每个输入" },
      { label: "B", text: "通过循环结构捕捉序列数据的时间依赖性" },
      { label: "C", text: "仅用于图像分类" },
      { label: "D", text: "无需激活函数" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "151",
    questionText: "LSTM 中“遗忘门”的作用是什么?",
    options: [
      { label: "A", text: "决定丢弃多少先前的信息" },
      { label: "B", text: "生成输出结果" },
      { label: "C", text: "增加新信息到细胞状态" },
      { label: "D", text: "计算注意力权重" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "152",
    questionText: "Transformer 模型的核心机制是什么?",
    options: [
      { label: "A", text: "卷积操作" },
      { label: "B", text: "池化操作" },
      { label: "C", text: "全连接层" },
      { label: "D", text: "自注意力机制" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "153",
    questionText: "Transformer 中“位置编码”的作用是什么?",
    options: [
      { label: "A", text: "引入非线性激活函数" },
      { label: "B", text: "为序列元素添加位置信息" },
      { label: "C", text: "减少参数量" },
      { label: "D", text: "直接生成输出结果" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "154",
    questionText: "BERT 模型的核心特点是什么?",
    options: [
      { label: "A", text: "使用单向 Transformer 编码器" },
      { label: "B", text: "仅用于图像分类" },
      { label: "C", text: "通过双向 Transformer 编码器学习文本表示" },
      { label: "D", text: "无需预训练" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "155",
    questionText: "Vision Transformer(ViT)如何将图像输入到 Transformer 中?",
    options: [
      { label: "A", text: "直接输入像素值" },
      { label: "B", text: "将图像分割为固定大小的补丁并视为序列" },
      { label: "C", text: "仅提取边缘信息" },
      { label: "D", text: "使用池化层压缩图像" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "156",
    questionText: "GPT 系列模型的主要生成方式是什么?",
    options: [
      { label: "A", text: "自回归方式预测下一个词" },
      { label: "B", text: "双向编码输入序列" },
      { label: "C", text: "仅用于图像生成" },
      { label: "D", text: "无需预训练" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "157",
    questionText: "以下哪项是 PyTorch 的主要特点?",
    options: [
      { label: "A", text: "仅支持静态计算图" },
      { label: "B", text: "动态计算图机制便于快速原型设计" },
      { label: "C", text: "仅用于自然语言处理" },
      { label: "D", text: "不支持 GPU 加速" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "158",
    questionText: "TensorFlow 的 TensorBoard 主要用于什么?",
    options: [
      { label: "A", text: "可视化训练过程和模型结构" },
      { label: "B", text: "生成图像数据" },
      { label: "C", text: "替代卷积操作" },
      { label: "D", text: "仅用于模型部署" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "159",
    questionText: "飞桨(PaddlePaddle)是哪家公司开发的深度学习框架?",
    options: [
      { label: "A", text: "谷歌" },
      { label: "B", text: "Facebook" },
      { label: "C", text: "百度" },
      { label: "D", text: "华为" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "160",
    questionText: "MindSpore 框架的核心优势之一是支持什么场景?",
    options: [
      { label: "A", text: "仅云端训练" },
      { label: "B", text: "端边云全场景覆盖" },
      { label: "C", text: "仅静态图模式" },
      { label: "D", text: "仅用于自然语言处理" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "161",
    questionText: "以下哪项是 CNN 中“卷积层”的作用?",
    options: [
      { label: "A", text: "直接输出分类结果" },
      { label: "B", text: "从输入数据中提取局部特征" },
      { label: "C", text: "仅用于降维" },
      { label: "D", text: "生成随机噪声" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "162",
    questionText: "在 Transformer 的解码器中,“编码器-解码器注意力层”的作用是什么?",
    options: [
      { label: "A", text: "防止未来位置信息流入当前位置" },
      { label: "B", text: "允许解码器关注编码器的输出" },
      { label: "C", text: "直接生成图像数据" },
      { label: "D", text: "仅用于池化操作" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "163",
    questionText: "在遥感图像分析中,计算机视觉主要用于:",
    options: [
      { label: "A", text: "实时视频流压缩" },
      { label: "B", text: "地表覆盖分类与灾害监测" },
      { label: "C", text: "语音指令识别" },
      { label: "D", text: "数据加密传输" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "164",
    questionText: "自动驾驶中,计算机视觉技术的核心功能是:",
    options: [
      { label: "A", text: "生成音乐推荐" },
      { label: "B", text: "实时检测行人、车辆及交通标志" },
      { label: "C", text: "优化电池续航" },
      { label: "D", text: "控制车内空调系统" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "165",
    questionText: "智慧医疗中,AI辅助诊断主要基于以下哪种技术处理医学影像?",
    options: [
      { label: "A", text: "自然语言处理(NLP)" },
      { label: "B", text: "计算机视觉与深度学习" },
      { label: "C", text: "区块链加密" },
      { label: "D", text: "量子计算" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "166",
    questionText: "文字识别(OCR)技术的关键步骤是:",
    options: [
      { label: "A", text: "图像边缘检测与字符分割" },
      { label: "B", text: "语音转文字" },
      { label: "C", text: "视频帧率调整" },
      { label: "D", text: "数据压缩存储" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "167",
    questionText: "增强现实(AR)中,计算机视觉的核心作用是:",
    options: [
      { label: "A", text: "实时跟踪物体位置与姿态" },
      { label: "B", text: "生成 3D模型动画" },
      { label: "C", text: "优化网络传输速度" },
      { label: "D", text: "加密用户数据" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "168",
    questionText: "遥感图像中检测非法采矿活动,最适合的计算机视觉任务是:",
    options: [
      { label: "A", text: "图像分类" },
      { label: "B", text: "目标检测" },
      { label: "C", text: "语义分割" },
      { label: "D", text: "实例分割" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "169",
    questionText: "自动驾驶中,多传感器融合主要解决:",
    options: [
      { label: "A", text: "计算功耗过高" },
      { label: "B", text: "单一传感器在恶劣天气下的局限性" },
      { label: "C", text: "用户界面设计" },
      { label: "D", text: "语音交互延迟" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "170",
    questionText: "医疗影像诊断中,AI 模型的挑战不包括:",
    options: [
      { label: "A", text: "数据隐私与伦理问题" },
      { label: "B", text: "模型可解释性不足" },
      { label: "C", text: "影像分辨率过高" },
      { label: "D", text: "标注数据稀缺" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "171",
    questionText: "手写文字识别属于计算机视觉的哪类任务?",
    options: [
      { label: "A", text: "图像生成" },
      { label: "B", text: "光学字符识别(OCR)" },
      { label: "C", text: "视频摘要" },
      { label: "D", text: "图像去噪" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "172",
    questionText: "AR 导航中,计算机视觉需结合:",
    options: [
      { label: "A", text: "实时定位与地图构建(SLAM )" },
      { label: "B", text: "语音合成技术" },
      { label: "C", text: "区块链验证" },
      { label: "D", text: "数据库索引优化" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "173",
    questionText: "遥感图像中,语义分割技术可用于:",
    options: [
      { label: "A", text: "区分农田与森林区域" },
      { label: "B", text: "压缩图像存储空间" },
      { label: "C", text: "增强图像对比度" },
      { label: "D", text: "生成三维地形图" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "174",
    questionText: "自动驾驶中,YOLO 算法的优势是:",
    options: [
      { label: "A", text: "单阶段检测,速度快" },
      { label: "B", text: "仅用于图像分类" },
      { label: "C", text: "依赖两阶段候选区域生成" },
      { label: "D", text: "仅处理静态图像" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "175",
    questionText: "医疗 AI诊断系统中,数据增强的作用是:",
    options: [
      { label: "A", text: "减少训练数据需求并提升泛化性" },
      { label: "B", text: "加密患者隐私信息" },
      { label: "C", text: "加快模型推理速度" },
      { label: "D", text: "降低图像分辨率" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "176",
    questionText: "文字识别中,处理倾斜文本的关键技术是:",
    options: [
      { label: "A", text: "图像仿射变换" },
      { label: "B", text: "增加字体大小" },
      { label: "C", text: "调整图像亮度" },
      { label: "D", text: "模糊处理" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "177",
    questionText: "遥感图像中,使用卷积神经网络(CNN)主要优势是:",
    options: [
      { label: "A", text: "自动提取多层次空间特征" },
      { label: "B", text: "减少数据存储需求" },
      { label: "C", text: "加速图像传输" },
      { label: "D", text: "增强色彩饱和度" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "178",
    questionText: "自动驾驶中,车道线检测通常采用:",
    options: [
      { label: "A", text: "边缘检测" },
      { label: "B", text: "语音识别算法" },
      { label: "C", text: "随机森林分类" },
      { label: "D", text: "生成对抗网络(GAN)" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "179",
    questionText: "医疗影像 AI 辅助诊断的伦理问题主要是:",
    options: [
      { label: "A", text: "数据隐私与算法透明度" },
      { label: "B", text: "图像分辨率不足" },
      { label: "C", text: "硬件成本过高" },
      { label: "D", text: "医生操作复杂度" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "180",
    questionText: "文字识别中,处理复杂背景干扰的常用方法是:",
    options: [
      { label: "A", text: "图像二值化与去噪" },
      { label: "B", text: "增加图像尺寸" },
      { label: "C", text: "降低色彩通道" },
      { label: "D", text: "随机裁剪图像" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "181",
    questionText: "卷积神经网络(CNN)中,池化层(Pooling)的主要作用是:",
    options: [
      { label: "A", text: "增加特征图的通道数" },
      { label: "B", text: "降低空间维度并增强平移不变性" },
      { label: "C", text: "直接输出分类结果" },
      { label: "D", text: "生成新的训练样本" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "182",
    questionText: "目标检测任务中,以下哪项是两阶段(Two-Stage)算法的代表?",
    options: [
      { label: "A", text: "YOLO" },
      { label: "B", text: "SSD" },
      { label: "C", text: "Faster R-CNN" },
      { label: "D", text: "RetinaNet" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "183",
    questionText: "以下哪种损失函数常用于二分类任务?",
    options: [
      { label: "A", text: "均方误差(MSE)" },
      { label: "B", text: "交叉熵损失(Cross-Entropy )" },
      { label: "C", text: "余弦相似度损失" },
      { label: "D", text: "对比损失(Contrastive Loss)" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "184",
    questionText: "在图像预处理中,归一化(Normalization)的主要目的是:",
    options: [
      { label: "A", text: "统一像素值范围,加速模型收敛" },
      { label: "B", text: "增加图像分辨率" },
      { label: "C", text: "生成对抗样本" },
      { label: "D", text: "减少图像存储空间" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "185",
    questionText: "以下哪种技术可以提升模型在遮挡场景下的目标检测性能?",
    options: [
      { label: "A", text: "非极大值抑制(NMS)" },
      { label: "B", text: "注意力机制(Attention)" },
      { label: "C", text: "图像锐化" },
      { label: "D", text: "降低学习率" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "186",
    questionText: "传统图像特征描述符(如 SIFT、HOG)与深度学习特征相比,主要劣势是:",
    options: [
      { label: "A", text: "依赖手工设计,泛化能力弱" },
      { label: "B", text: "计算速度更快" },
      { label: "C", text: "对旋转不变性更好" },
      { label: "D", text: "适合小数据集" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "187",
    questionText: "实时视频处理中,计算机视觉系统通常需要优先优化:",
    options: [
      { label: "A", text: "算法计算效率(FPS)" },
      { label: "B", text: "模型参数量" },
      { label: "C", text: "训练数据量" },
      { label: "D", text: "图像色彩饱和度" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "188",
    questionText: "以下哪种模型首次将 Transformer 引入计算机视觉领域?",
    options: [
      { label: "A", text: "ResNet" },
      { label: "B", text: "Vision Transformer (ViT)" },
      { label: "C", text: "YOLOv4" },
      { label: "D", text: "U-Net" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "189",
    questionText: "YOLO (You Only Look Once)的核心思想是:",
    options: [
      { label: "A", text: "将图像划分为网格,每个网格预测多个边界框" },
      { label: "B", text: "生成候选区域后进行分类与回归" },
      { label: "C", text: "仅支持单类别检测" },
      { label: "D", text: "依赖两阶段检测流程" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "190",
    questionText: "R-CNN的第一步操作通常是:",
    options: [
      { label: "A", text: "使用 Selective Search 生成候选区域" },
      { label: "B", text: "训练区域建议网络(RPN )" },
      { label: "C", text: "对全图进行卷积特征提取" },
      { label: "D", text: "直接回归边界框坐标" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "191",
    questionText: "Fast R-CNN 相比R-CNN 的主要改进是:",
    options: [
      { label: "A", text: "引入 ROI Pooling 共享卷积特征" },
      { label: "B", text: "使用 RPN 生成候选区域" },
      { label: "C", text: "增加掩码预测分支" },
      { label: "D", text: "改用单阶段检测流程" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "192",
    questionText: "Faster R-CNN 的核心创新是:",
    options: [
      { label: "A", text: "用 RPN(Region Proposal Network)替代 Selective Search" },
      { label: "B", text: "引入多任务损失函数" },
      { label: "C", text: "支持实例分割" },
      { label: "D", text: "提高检测速度至实时" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "193",
    questionText: "YOLO与Faster R-CNN 的主要区别是:",
    options: [
      { label: "A", text: "YOLO 是单阶段检测,Faster R-CNN 是两阶段" },
      { label: "B", text: "YOLO 依赖候选区域生成" },
      { label: "C", text: "Faster R-CNN 不支持多类别检测" },
      { label: "D", text: "YOLO 仅用于图像分割" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "194",
    questionText: "ROI Align 在 Mask R-CNN 中的作用是:",
    options: [
      { label: "A", text: "解决 ROI Pooling 的量化误差,提升掩码精度" },
      { label: "B", text: "加速候选区域生成" },
      { label: "C", text: "减少模型训练时间" },
      { label: "D", text: "增强图像对比度" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "195",
    questionText: "非极大值抑制(NMS)在目标检测中的作用是:",
    options: [
      { label: "A", text: "去除冗余的候选框,保留最佳预测" },
      { label: "B", text: "增加候选框数量" },
      { label: "C", text: "提升特征图分辨率" },
      { label: "D", text: "优化损失函数" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "196",
    questionText: "Faster R-CNN的RPN 网络输出包括:",
    options: [
      { label: "A", text: "候选框的位置偏移和类别得分" },
      { label: "B", text: "像素级分割掩码" },
      { label: "C", text: "图像分类结果" },
      { label: "D", text: "光流运动向量" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "197",
    questionText: "两阶段检测算法(如 Faster R-CNN)相比单阶段(如 YOLO)的优势通常是:",
    options: [
      { label: "A", text: "检测精度更高" },
      { label: "B", text: "推理速度更快" },
      { label: "C", text: "模型参数量更小" },
      { label: "D", text: "无需标注数据" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "198",
    questionText: "YOLO 的损失函数包含以下哪项?",
    options: [
      { label: "A", text: "边界框坐标误差、置信度误差、分类误差" },
      { label: "B", text: "仅分类误差" },
      { label: "C", text: "掩码预测误差" },
      { label: "D", text: "光流估计误差" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "199",
    questionText: "Fast R-CNN 的 ROI Pooling 层将候选区域映射到:",
    options: [
      { label: "A", text: "固定大小的特征图" },
      { label: "B", text: "原始图像分辨率" },
      { label: "C", text: "随机尺寸特征图" },
      { label: "D", text: "一维向量" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "200",
    questionText: "R-CNN的候选区域生成方法(Selective Search)属于:",
    options: [
      { label: "A", text: "传统无监督方法" },
      { label: "B", text: "深度学习模型" },
      { label: "C", text: "强化学习策略" },
      { label: "D", text: "生成对抗网络" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "201",
    questionText: "YOLO 的缺点主要是:",
    options: [
      { label: "A", text: "对小目标和密集目标检测效果较差" },
      { label: "B", text: "无法实时推理" },
      { label: "C", text: "仅支持两阶段检测" },
      { label: "D", text: "依赖手动设计候选区域" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "202",
    questionText: "Faster R-CNN的RPN与Fast R-CNN的关系是:",
    options: [
      { label: "A", text: "RPN 替代了Fast R-CNN 的 Selective Search" },
      { label: "B", text: "RPN用于分类候选区域" },
      { label: "C", text: "Fast R-CNN包含RPN" },
      { label: "D", text: "两者无直接关联" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "203",
    questionText: "Mask R-CNN可以同时完成的任务是:",
    options: [
      { label: "A", text: "目标检测和实例分割" },
      { label: "B", text: "仅目标分类" },
      { label: "C", text: "图像超分辨率" },
      { label: "D", text: "视频动作识别" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "204",
    questionText: "以下哪种模型最适合需要高精度实例分割的场景?",
    options: [
      { label: "A", text: "Mask R-CNN" },
      { label: "B", text: "YOLOV5" },
      { label: "C", text: "Fast R-CNN" },
      { label: "D", text: "R-CNN" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "205",
    questionText: "语言在机器中的哪一种表示有利于进行语义相似性的计算?",
    options: [
      { label: "A", text: "独热编码;" },
      { label: "B", text: "ASCII 码;" },
      { label: "C", text: "UTF-8编码;" },
      { label: "D", text: "词向量" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "206",
    questionText: "机器在建模语言问题用什么方法处理不确定性预测?",
    options: [
      { label: "A", text: "对输出进行概率建模;" },
      { label: "B", text: "使用神经网络;" },
      { label: "C", text: "梯度优化方法;" },
      { label: "D", text: "学习函数关系" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "207",
    questionText: "语言模型的核心目标是什么?",
    options: [
      { label: "A", text: "生成随机文本;" },
      { label: "B", text: "预测一段文本的概率分布;" },
      { label: "C", text: "识别图像中的文字;" },
      { label: "D", text: "翻译不同语言" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "208",
    questionText: "____是一类预测模型,它假设当前时间点的输出仅依赖于之前的输出。",
    options: [
      { label: "A", text: "神经网络;" },
      { label: "B", text: "回归模型;" },
      { label: "C", text: "自回归语言模型;" },
      { label: "D", text: "分类模型" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "209",
    questionText: "目前研究表明大模型的参数数量与效果之间的关系符合____。",
    options: [
      { label: "A", text: "大数定律" },
      { label: "B", text: "尺度定律 (Scaling Law)" },
      { label: "C", text: "中心极限定理" },
      { label: "D", text: "万能近似定理" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "210",
    questionText: "以下哪种情况最可能导致模型产生幻觉?",
    options: [
      { label: "A", text: "训练数据中包含大量噪声或错误信息" },
      { label: "B", text: "模型参数量过小" },
      { label: "C", text: "用户输入过于简短" },
      { label: "D", text: "使用过高的温度(Temperature)参数" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "211",
    questionText: "以下哪种方法被广泛用于缓解模型幻觉问题?",
    options: [
      { label: "A", text: "提高模型的推理速度" },
      { label: "B", text: "增加模型层数" },
      { label: "C", text: "引入外部知识库进行事实性验证" },
      { label: "D", text: "减少训练数据规模" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "212",
    questionText: "幻觉问题在以下哪个任务中影响最严重?",
    options: [
      { label: "A", text: "情感分析" },
      { label: "B", text: "机器翻译" },
      { label: "C", text: "医疗诊断建议生成" },
      { label: "D", text: "文本摘要" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "213",
    questionText: "哪种模型架构设计能有效减少幻觉?",
    options: [
      { label: "A", text: "纯解码器架构(如GPT)" },
      { label: "B", text: "编码器-解码器架构(如 T5)" },
      { label: "C", text: "检索增强生成(RAG)" },
      { label: "D", text: "卷积神经网络(CNN)" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "214",
    questionText: "以下哪种提示(Prompt)策略有助于降低幻觉风险?",
    options: [
      { label: "A", text: "要求模型“自由发挥想象力”" },
      { label: "B", text: "明确要求“仅基于可信来源回答”" },
      { label: "C", text: "使用开放式问题" },
      { label: "D", text: "提供大量无关联的示例" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "215",
    questionText: "词向量的核心目标是什么?",
    options: [
      { label: "A", text: "将词语转换为独热编码(One-Hot Encoding )" },
      { label: "B", text: "在低维连续向量空间中捕捉词语的语义和语法关系" },
      { label: "C", text: "提高文本分类任务的速度" },
      { label: "D", text: "减少词典大小" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "216",
    questionText: "词向量之间的余弦相似度通常用于衡量什么?",
    options: [
      { label: "A", text: "词语的拼写相似性" },
      { label: "B", text: "词语的语义相似性" },
      { label: "C", text: "句子的语法复杂度" },
      { label: "D", text: "文本的情感极性" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "217",
    questionText: "以下哪种应用场景最依赖语言模型?",
    options: [
      { label: "A", text: "人脸识别" },
      { label: "B", text: "机器翻译" },
      { label: "C", text: "自动驾驶路径规划" },
      { label: "D", text: "医学影像分析" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "218",
    questionText: "GPT(生成式预训练模型)的核心特点是?",
    options: [
      { label: "A", text: "仅支持文本分类任务" },
      { label: "B", text: "基于自回归生成(逐词生成文本)" },
      { label: "C", text: "仅使用图像数据训练" },
      { label: "D", text: "模型参数量固定为1亿" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "219",
    questionText: "以下哪种技术能帮助语言模型理解用户意图?",
    options: [
      { label: "A", text: "数据增强(Data Augmentation)" },
      { label: "B", text: "指令微调(Instruction Tuning )" },
      { label: "C", text: "随机森林分类器" },
      { label: "D", text: "图像分割" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "220",
    questionText: "大模型“涌现能力”(Emergent Ability)指的是:",
    options: [
      { label: "A", text: "模型参数越多,训练速度越快" },
      { label: "B", text: "小模型表现优于大模型" },
      { label: "C", text: "模型在参数量达到阈值后突然具备新能力" },
      { label: "D", text: "模型自动删除无用数据" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "221",
    questionText: "在自然语言处理中,“词向量”(Word Embedding)的作用是:",
    options: [
      { label: "A", text: "将词语转换为计算机可理解的数值向量" },
      { label: "B", text: "压缩文本文件大小" },
      { label: "C", text: "生成艺术风格图片" },
      { label: "D", text: "优化硬盘存储空间" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "222",
    questionText: "以下哪项技术可以帮助大模型减少生成不真实内容(如虚构事实)的问题?",
    options: [
      { label: "A", text: "增加模型参数规模" },
      { label: "B", text: "使用更高精度的浮点数" },
      { label: "C", text: "与搜索引擎实时结合验证" },
      { label: "D", text: "提高训练数据压缩率" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "223",
    questionText: "大语言模型(如 ChatGPT)的“预训练”阶段主要学习的是:",
    options: [
      { label: "A", text: "特定任务(如翻译)的标注数据" },
      { label: "B", text: "海量无标注文本中的语言规律" },
      { label: "C", text: "如何操作机器人手臂" },
      { label: "D", text: "数学公式推导" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "224",
    questionText: "以下哪个是自然语言处理的典型应用?",
    options: [
      { label: "A", text: "人脸识别解锁手机" },
      { label: "B", text: "智能客服自动回复问题" },
      { label: "C", text: "自动驾驶汽车避障" },
      { label: "D", text: "无人机航拍摄影" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "225",
    questionText: "自然语言处理(NLP)的主要目标是让计算机能够:",
    options: [
      { label: "A", text: "播放高清视频" },
      { label: "B", text: "理解和生成人类语言" },
      { label: "C", text: "识别图像中的物体" },
      { label: "D", text: "控制机器人行走" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "226",
    questionText: "以下哪种方法可以降低大模型的碳排放?",
    options: [
      { label: "A", text: "使用更多 GPU 集群训练" },
      { label: "B", text: "采用更高效的模型架构" },
      { label: "C", text: "增加训练数据量" },
      { label: "D", text: "提高模型参数量" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "227",
    questionText: "以下哪个任务不属于自然语言处理(NLP)的典型应用?",
    options: [
      { label: "A", text: "机器翻译" },
      { label: "B", text: "情感分析" },
      { label: "C", text: "图像分类" },
      { label: "D", text: "文本摘要" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "228",
    questionText: "Transformer 模型的核心机制是?",
    options: [
      { label: "A", text: "循环神经网络(RNN)" },
      { label: "B", text: "卷积神经网络(CNN)" },
      { label: "C", text: "注意力机制(Attention)" },
      { label: "D", text: "强化学习(Reinforcement Learning )" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "229",
    questionText: "大模型伦理问题中的“幻觉”(Hallucination)指什么?",
    options: [
      { label: "A", text: "模型生成重复内容" },
      { label: "B", text: "模型生成与输入无关的虚假信息" },
      { label: "C", text: "模型训练速度过慢" },
      { label: "D", text: "模型无法处理长文本" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "230",
    questionText: "模型幻觉问题的根本原因可能包括:",
    options: [
      { label: "A", text: "训练数据与真实世界知识存在偏差" },
      { label: "B", text: "模型参数量过大" },
      { label: "C", text: "GPU 显存不足" },
      { label: "D", text: "用户输入语法错误" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "231",
    questionText: "知识图谱的核心目标是什么?",
    options: [
      { label: "A", text: "存储海量非结构化文本" },
      { label: "B", text: "通过结构化语义网络描述实体及其关系" },
      { label: "C", text: "加速图像识别任务" },
      { label: "D", text: "优化神经网络训练速度" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "232",
    questionText: "以下哪种数据库类型最适合存储知识图谱?",
    options: [
      { label: "A", text: "关系型数据库(如 MySQL)" },
      { label: "B", text: "文档数据库(如 MongoDB)" },
      { label: "C", text: "键值数据库(如 Redis)" },
      { label: "D", text: "图数据库(如Neo4j)" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "233",
    questionText: "知识图谱构建的关键步骤不包括:",
    options: [
      { label: "A", text: "实体识别" },
      { label: "B", text: "关系抽取" },
      { label: "C", text: "图像分类" },
      { label: "D", text: "知识融合" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "234",
    questionText: "知识图谱的典型应用场景是?",
    options: [
      { label: "A", text: "图像风格迁移" },
      { label: "B", text: "语音信号降噪" },
      { label: "C", text: "智能问答系统(如谷歌搜索)" },
      { label: "D", text: "视频压缩编码" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "235",
    questionText: "知识图谱与传统数据库的核心区别在于?",
    options: [
      { label: "A", text: "存储容量更大" },
      { label: "B", text: "强调实体间的语义关联" },
      { label: "C", text: "支持事务处理" },
      { label: "D", text: "读写速度更快" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "236",
    questionText: "知识图谱的“本体(Ontology)”主要用于:",
    options: [
      { label: "A", text: "定义实体类别与关系的逻辑约束" },
      { label: "E", text: "优化图数据库的存储效率" }, // Assuming this was a typo for B
      { label: "F", text: "压缩知识表示空间" }, // Assuming this was a typo for C
      { label: "G", text: "生成自然语言描述" }, // Assuming this was a typo for D
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "237",
    questionText: "知识图谱一种结构化的语义知识库,将知识以____的形式存下来?",
    options: [
      { label: "A", text: "数组" },
      { label: "B", text: "树" },
      { label: "C", text: "图" },
      { label: "D", text: "表" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "238",
    questionText: "以下哪个不是知识图谱的主要组成部分?",
    options: [
      { label: "A", text: "边" },
      { label: "B", text: "节点" },
      { label: "C", text: "关系事实" },
      { label: "D", text: "本体" }, 
    ],
    correctAnswerLabel: "D", 
  },
  {
    id: "239",
    questionText: "在知识图谱中,实体可以是?",
    options: [
      { label: "A", text: "实例" },
      { label: "B", text: "数值" },
      { label: "C", text: "时间" },
      { label: "D", text: "某人出生于某地" }, 
    ],
    correctAnswerLabel: "D", 
  },
  {
    id: "240",
    questionText: "知识图谱通常用____来表示。",
    options: [
      { label: "A", text: "数值向量" },
      { label: "B", text: "字符串序列" },
      { label: "C", text: "有向图" },
      { label: "D", text: "二叉树" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "241",
    questionText: "____是一种结合了信息检索技术和大型语言模型生成的人工智能技术。",
    options: [
      { label: "A", text: "检索增强生成(简称RAG)" },
      { label: "B", text: "知识图谱" },
      { label: "C", text: "本体" },
      { label: "D", text: "模型压缩" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "242",
    questionText: "检索增强生成(RAG)的核心思想是?",
    options: [
      { label: "A", text: "仅依赖生成模型内部知识;" },
      { label: "B", text: "结合检索外部知识库与生成模型的能力;" },
      { label: "C", text: "完全替代传统搜索引擎;" },
      { label: "D", text: "仅优化生成模型的推理速度" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "243",
    questionText: "检索增强生成(RAG)模型的工作流程通常分为哪两个主要阶段?",
    options: [
      { label: "A", text: "训练与微调" },
      { label: "B", text: "检索与生成" },
      { label: "C", text: "编码与解码" },
      { label: "D", text: "分词与向量化" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "244",
    questionText: "检索增强生成(RAG)相比纯生成模型(如 GPT)的主要优势是?",
    options: [
      { label: "A", text: "减少模型参数量;" },
      { label: "B", text: "降低对训练数据量的依赖;" },
      { label: "C", text: "提高生成内容的事实准确性;" },
      { label: "D", text: "完全消除生成重复文本的问题" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "245",
    questionText: "莫拉维克悖论的核心观点是以下哪一项?",
    options: [
      { label: "A", text: "人类的高级逻辑推理能力难以被机器模仿" },
      { label: "B", text: "一些对人类来说简单的感知和运动技能,机器实现起来反而比高级推理困难" },
      { label: "C", text: "人类和机器在低级技能上的学习速度相同" },
      { label: "D", text: "机器无法进行复杂的数学计算" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "246",
    questionText: "以下哪项是莫拉维克悖论的典型例子?",
    options: [
      { label: "A", text: "AlphaGo 难以击败围棋世界冠军" },
      { label: "B", text: "机器人依靠复杂技术完成了叠衣服这一简单的任务" },
      { label: "C", text: "自动驾驶汽车可以识别交通信号灯" },
      { label: "D", text: "语音助手可以用于回答问题" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "247",
    questionText: "莫拉维克悖论的提出者不包括以下哪位?",
    options: [
      { label: "A", text: "汉斯·莫拉维克" },
      { label: "B", text: "罗德尼·布鲁克斯" },
      { label: "C", text: "马文·明斯基" },
      { label: "D", text: "艾伦·图灵" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "248",
    questionText: "强化学习的核心机制是?",
    options: [
      { label: "A", text: "通过监督数据优化模型" },
      { label: "B", text: "通过试错和奖励信号调整策略" },
      { label: "C", text: "基于无标签数据聚类" },
      { label: "D", text: "依赖先验知识直接决策" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "249",
    questionText: "马尔可夫决策过程(MDP)的五元组不包括以下哪项?",
    options: [
      { label: "A", text: "状态空间(S)" },
      { label: "B", text: "动作空间(A)" },
      { label: "C", text: "奖励函数(R)" },
      { label: "D", text: "学习率(α)" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "250",
    questionText: "下列哪一项符合深度强化学习的特点?",
    options: [
      { label: "A", text: "结合监督学习和无监督学习" },
      { label: "B", text: "使用神经网络处理高维和连续的状态输入" },
      { label: "C", text: "仅依赖无监督学习" },
      { label: "D", text: "完全不需要环境交互" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "251",
    questionText: "AlphaGo 的成功主要使用了哪两项技术的结合?",
    options: [
      { label: "A", text: "规划技术与无监督学习" },
      { label: "B", text: "强化学习与深度学习" },
      { label: "C", text: "聚类分析与逻辑回归" },
      { label: "D", text: "卷积神经网络与循环神经网络" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "252",
    questionText: "强化学习中的折扣因子γ的主要作用是?",
    options: [
      { label: "A", text: "调整学习率" },
      { label: "B", text: "是折扣累计回报G的核心参数,用于调节当前奖励与未来奖励的重要性" },
      { label: "C", text: "限制动作空间大小" },
      { label: "D", text: "限制状态空间大小" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "253",
    questionText: "关于强化学习与监督学习,下面哪一个说法正确?",
    options: [
      { label: "A", text: "两者都需要大量标注独立同分布数据" },
      { label: "B", text: "强化学习依赖试错和延迟奖励" },
      { label: "C", text: "监督学习主要用于处理连续决策问题" },
      { label: "D", text: "两者都基于规则推理" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "254",
    questionText: "在强化学习中,智能体的最终目标是最大化什么?",
    options: [
      { label: "A", text: "单步奖励" },
      { label: "B", text: "累计折扣奖励" },
      { label: "C", text: "动作执行速度" },
      { label: "D", text: "状态转移频率" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "255",
    questionText: "关于环境分类,以下哪个智能体的环境是完全可观察的?",
    options: [
      { label: "A", text: "自动驾驶出租车" },
      { label: "B", text: "医疗诊断智能体" },
      { label: "C", text: "围棋 AlphaGo" },
      { label: "D", text: "零件挑选机器人" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "256",
    questionText: "在强化学习中,策略(Policy)的功能是?",
    options: [
      { label: "A", text: "感知环境状态" },
      { label: "B", text: "执行物理动作" },
      { label: "C", text: "定义状态到动作的映射" },
      { label: "D", text: "计算即时奖励" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "257",
    questionText: "HumanPlus 机器人训练中使用的强化学习算法是?",
    options: [
      { label: "A", text: "Q-learning" },
      { label: "B", text: "近端策略优化(PPO)" },
      { label: "C", text: "深度确定性策略梯度(DDPG)" },
      { label: "D", text: "基于模型的强化学习算法" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "258",
    questionText: "以下哪种不是定义智能体的规则()",
    options: [
      { label: "A", text: "需要具备识别环境的能力" },
      { label: "B", text: "根据观察做出决定" },
      { label: "C", text: "决定应该导致行动" },
      { label: "D", text: "行动可以是随意的" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "259",
    questionText: "以下关于智能体的说法,哪些是不正确的()",
    options: [
      { label: "A", text: "智能体是任何可以通过传感器感知其环境并通过执行器对环境进行作用的主体" },
      { label: "B", text: "智能体根据观察做出决定" },
      { label: "C", text: "智能体基于它的感知及它能执行的行动“做正确的事”" },
      { label: "D", text: "理性智能体知道他行动的实际效果并做出行动获得完美结果" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "260",
    questionText: "智能体的理性不取决于以下哪个选项()",
    options: [
      { label: "A", text: "给定的性能度量" },
      { label: "B", text: "自身动作的随机性" },
      { label: "C", text: "内在的先验知识" },
      { label: "D", text: "感知序列" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "261",
    questionText: "智能体的任务环境描述不包含下面哪个选项()",
    options: [
      { label: "A", text: "性能度量" },
      { label: "B", text: "环境" },
      { label: "C", text: "状态空间" },
      { label: "D", text: "执行器" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "262",
    questionText: "以下哪一项不属于医疗诊断智能体的PEAS 任务环境()",
    options: [
      { label: "A", text: "医院" },
      { label: "B", text: "医生的行医执照" },
      { label: "C", text: "触摸屏" },
      { label: "D", text: "疾病诊断准确性" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "263",
    questionText: "以下哪一项不能作为智能体环境类型的分类依据()",
    options: [
      { label: "A", text: "传感器是否获取环境的所有状态" },
      { label: "B", text: "智能体的决策是否需要获取环境状态" },
      { label: "C", text: "环境的下一个状态是否完全取决于当前状态和智能体的行动" },
      { label: "D", text: "智能体当前行动的选择是否不依赖于以前的行动" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "264",
    questionText: "以下关于环境类型的说法哪项是正确的()",
    options: [
      { label: "A", text: "自动驾驶任务中环境是完全可观察的" },
      { label: "B", text: "围棋任务中环境中环境是部分可观察的" },
      { label: "C", text: "零件挑选机器人的任务环境是动态的" },
      { label: "D", text: "自动驾驶任务中环境是离散的" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "265",
    questionText: "以下关于自动驾驶环境类型的说法哪项是不正确的()",
    options: [
      { label: "A", text: "自动驾驶任务中对环境的感知是片段的" },
      { label: "B", text: "自动驾驶任务环境中环境的变化不完全取决于智能体的行为" },
      { label: "C", text: "自动驾驶中环境是动态的" },
      { label: "D", text: "自动驾驶是单智能体环境任务" },
    ],
    correctAnswerLabel: "D", 
  },
  {
    id: "266",
    questionText: "以下关于医疗诊断智能体环境类型的说法哪项是正确的()",
    options: [
      { label: "A", text: "环境是部分可观察的" },
      { label: "B", text: "环境下一状态完全取决于智能体行动" },
      { label: "C", text: "环境随智能体思考发生改变" },
      { label: "D", text: "是多智能体任务环境" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "267",
    questionText: "关于智能体的分类,以下哪个不属于智能体的基本类型()",
    options: [
      { label: "A", text: "简单反射型智能体" },
      { label: "B", text: "基于模型的反射型智能体" },
      { label: "C", text: "理性智能体" },
      { label: "D", text: "基于目标的智能体" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "268",
    questionText: "对于表驱动的智能体,以下那种说法是不正确的()",
    options: [
      { label: "A", text: "构建一个表记录所有的感知序列及其最佳行动" },
      { label: "B", text: "智能体在运行时会根据感知,通过查表方式来决定行动" },
      { label: "C", text: "一般很容易获取查询表的所有条目" },
      { label: "D", text: "需要花费大量的时间构建表,甚至无法构建" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "269",
    questionText: "以下关于简单反射型智能体说法不正确的是()",
    options: [
      { label: "A", text: "简单反射型智能体基于状态-动作规则进行决策" },
      { label: "B", text: "需要与环境进行交互" },
      { label: "C", text: "基于当前的感知选择行动,不涉及目标、效用等信息" },
      { label: "D", text: "需要基于感知历史进行决策" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "270",
    questionText: "以下关于基于目标的智能体说法不正确的是()",
    options: [
      { label: "A", text: "为了达到目标选择合适的行动" },
      { label: "B", text: "只考虑一个短期看起来有利的行动并执行" },
      { label: "C", text: "为达到目标,可能会考虑一个很长的可能行动序列" },
      { label: "D", text: "会思考如果执行这个行为后,世界会怎样变化" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "271",
    questionText: "以下关于基于效用的智能体说法不正确的是()",
    options: [
      { label: "A", text: "需要与环境交互" },
      { label: "B", text: "需要更通用的性能度量" },
      { label: "C", text: "智能体的决策过程中涉及到效用函数的使用" },
      { label: "D", text: "性能度量的反馈信息比较单一" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "272",
    questionText: "以下关于学习智能体说法不正确的是()",
    options: [
      { label: "A", text: "以基本知识开始执行动作,能够通过学习自动行动与适应" },
      { label: "B", text: "学习元素从评价器获得反馈,这些反馈描述了智能体在固定性能标准方面的表现" },
      { label: "C", text: "不需要行动的反馈" },
      { label: "D", text: "需要从环境中学习" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "273",
    questionText: "以下哪一项是机器人的基本组成?",
    options: [
      { label: "A", text: "传感器、处理器、效应器" },
      { label: "B", text: "显示器、键盘、鼠标" },
      { label: "C", text: "电池、外壳、轮子" },
      { label: "D", text: "软件、硬件、网络" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "274",
    questionText: "下列关于机器人的说法中,正确的是:",
    options: [
      { label: "A", text: "所有机器人都需要人工控制" },
      { label: "B", text: "机器人只能在工厂中使用" },
      { label: "C", text: "机器人是一种具备感知、决策和执行能力的智能系统" },
      { label: "D", text: "机器人不具备自主性" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "275",
    questionText: "机器人被称为“智能决策的实体”,是因为它能:",
    options: [
      { label: "A", text: "模拟人类行为" },
      { label: "B", text: "独立完成所有任务" },
      { label: "C", text: "具备感知、处理和执行的能力" },
      { label: "D", text: "完全替代人类" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "276",
    questionText: "激光雷达属于哪类传感器?",
    options: [
      { label: "A", text: "无源传感器" },
      { label: "B", text: "温度传感器" },
      { label: "C", text: "有源传感器" },
      { label: "D", text: "接触式传感器" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "277",
    questionText: "机器人“看见”前方物体,是通过哪个部件完成的?",
    options: [
      { label: "A", text: "机械臂" },
      { label: "B", text: "传感器" },
      { label: "C", text: "处理器" },
      { label: "D", text: "执行器" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "278",
    questionText: "有源传感器与无源传感器的主要区别是:",
    options: [
      { label: "A", text: "有源传感器更容易安装和部署" },
      { label: "B", text: "有源传感器主动发出信号" },
      { label: "C", text: "无源传感器使用电池" },
      { label: "D", text: "无源传感器只能探测金属" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "279",
    questionText: "机器人进行逻辑推理和决策主要依靠哪个部件?",
    options: [
      { label: "A", text: "传感器" },
      { label: "B", text: "摄像头" },
      { label: "C", text: "处理器" },
      { label: "D", text: "电源" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "280",
    questionText: "下列哪个选项可以作为机器人的“眼睛”:",
    options: [
      { label: "A", text: "电源" },
      { label: "B", text: "红外传感器" },
      { label: "C", text: "激光切割装置" },
      { label: "D", text: "电机" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "281",
    questionText: "机器人进行自我判断并选择行为的能力来自于:",
    options: [
      { label: "A", text: "数据库" },
      { label: "B", text: "决策程序" },
      { label: "C", text: "执行机构" },
      { label: "D", text: "能源系统" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "282",
    questionText: "机器人将感知信息转为行动指令的是:",
    options: [
      { label: "A", text: "电源系统" },
      { label: "B", text: "通信模块" },
      { label: "C", text: "处理器" },
      { label: "D", text: "液压机构" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "283",
    questionText: "有源传感器最大的优势是:",
    options: [
      { label: "A", text: "造价低" },
      { label: "B", text: "主动感知并构建环境模型" },
      { label: "C", text: "可以完全替代人类视觉" },
      { label: "D", text: "不依赖电源" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "284",
    questionText: "以下关于机器人自主性的描述,正确的是:",
    options: [
      { label: "A", text: "工业机械臂完全不能适应环境变化" },
      { label: "B", text: "扫地机器人能根据房间布局自主规划路径" },
      { label: "C", text: "火星车需要人工操作每一个动作" },
      { label: "D", text: "手术机器人不依赖任何预设程序" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "285",
    questionText: "机器人系统中,三大核心模块的协作流程正确顺序是:",
    options: [
      { label: "A", text: "效应器 → 传感器 → 处理器" },
      { label: "B", text: "处理器 → 传感器 → 效应器" },
      { label: "C", text: "传感器 → 处理器 → 效应器" },
      { label: "D", text: "电源 → 执行器 → 显示器" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "286",
    questionText: "以下哪项不属于人工智能自身的内生风险?",
    options: [
      { label: "A", text: "自动驾驶系统错误决策导致事故" },
      { label: "B", text: "医疗 AI 因数据保护不力泄露隐私" },
      { label: "C", text: "生成模型伪造虚假新闻误导公众" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "287",
    questionText: "AI 安全研究的核心目标之一是提升模型的____,即模型在噪声、干扰或恶意攻击下仍能保持稳定输出的能力。",
    options: [
      { label: "A", text: "透明性" },
      { label: "B", text: "鲁棒性" },
      { label: "C", text: "公平性" },
      { label: "D", text: "可解释性" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "288",
    questionText: "以下哪项属于AI 伦理治理中“透明性”原则的具体要求?",
    options: [
      { label: "A", text: "确保模型训练数据来源合法" },
      { label: "B", text: "保证用户不滥用 AI" },
      { label: "C", text: "向用户说明 AI 决策逻辑与依据" },
      { label: "D", text: "限制模型的使用场景" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "289",
    questionText: "为防范数据泄露风险,AI开发中应优先采取的措施是______。",
    options: [
      { label: "A", text: "清洗训练数据中的有害内容" },
      { label: "B", text: "使用差分隐私技术" },
      { label: "C", text: "提高训练数据规模" },
      { label: "D", text: "部署模型压缩工具" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "290",
    questionText: "在AI 安全伦理风险防范技术中,通过调整训练过程使模型对输入扰动更鲁棒的方法是____。",
    options: [
      { label: "A", text: "数据增广" },
      { label: "B", text: "对抗训练" },
      { label: "C", text: "数据生成" }, 
      { label: "D", text: "价值对齐" }, 
    ],
    correctAnswerLabel: "B", 
  },
  {
    id: "291",
    questionText: "以下哪项不属于 AI 伦理指导原则中的关键要求?",
    options: [
      { label: "A", text: "透明性" },
      { label: "B", text: "数据生成" },
      { label: "C", text: "隐私保护" },
      { label: "D", text: "公平性" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "292",
    questionText: "AI技术对社会就业的冲击属于以下哪种风险?",
    options: [
      { label: "A", text: "内生风险" },
      { label: "B", text: "衍生风险" },
      { label: "C", text: "技术漏洞" },
      { label: "D", text: "数据偏见" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "293",
    questionText: "以下哪项属于AI系统的内生风险?",
    options: [
      { label: "A", text: "生成虚假新闻误导公众" },
      { label: "B", text: "模型决策过程不可解释" },
      { label: "C", text: "技术滥用导致劳资矛盾" },
      { label: "D", text: "自动化取代传统岗位" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "294",
    questionText: "公平性风险的主要产生原因不包括以下哪一项?",
    options: [
      { label: "A", text: "训练数据中的历史偏见" },
      { label: "B", text: "模型优化目标忽略公平性约束" },
      { label: "C", text: "训练过程中缺乏偏见检测算法" },
      { label: "D", text: "模型无法理解用户指令" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "295",
    questionText: "有害性风险仅涉及生成暴力、色情等恶意内容,不包括伦理问题。这句话是否正确?",
    options: [
      { label: "A", text: "正确" },
      { label: "B", text: "错误" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "296",
    questionText: "人工智能模型在微调后丢失原有知识的现象称为____。",
    options: [
      { label: "A", text: "数据偏差" },
      { label: "B", text: "灾难性遗忘" },
      { label: "C", text: "过拟合" },
      { label: "D", text: "训练不稳定" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "297",
    questionText: "以下哪项属于可靠性风险的典型表现?",
    options: [
      { label: "A", text: "生成种族歧视言论" },
      { label: "B", text: "输出与输入指令无关的内容" },
      { label: "C", text: "导致就业市场失衡" },
      { label: "D", text: "教唆用户自残" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "298",
    questionText: "人工智能滥用导致的学术造假和就业市场失衡属于衍生风险问题。这句话是否正确?",
    options: [
      { label: "A", text: "正确" },
      { label: "B", text: "错误" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "299",
    questionText: "训练数据中包含未清洗的暴力内容,可能导致模型输出____风险。",
    options: [
      { label: "A", text: "公平性" },
      { label: "B", text: "可靠性" },
      { label: "C", text: "有害性" },
      { label: "D", text: "安全性" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "300",
    questionText: "以下哪项是模型优化目标忽略公平性约束的直接后果?",
    options: [
      { label: "A", text: "提高模型推理速度" },
      { label: "B", text: "加剧对特定群体的系统性偏见" },
      { label: "C", text: "减少训练数据需求量" },
      { label: "D", text: "增强模型泛化能力" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "301",
    questionText: "面部识别系统对非洲裔女性错误率较高,主要反映了____风险。",
    options: [
      { label: "A", text: "可靠性" },
      { label: "B", text: "有害性" },
      { label: "C", text: "公平性" },
      { label: "D", text: "安全性" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "302",
    questionText: "模型鲁棒性差最可能表现为以下哪种情况?",
    options: [
      { label: "A", text: "在对抗样本攻击下输出错误结果" },
      { label: "B", text: "训练时需要大量计算资源" },
      { label: "C", text: "用户界面设计不友好" },
      { label: "D", text: "模型文件体积过大" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "303",
    questionText: "通过黑盒访问接口复制目标模型参数信息的攻击方式属于____。",
    options: [
      { label: "A", text: "成员推断攻击" },
      { label: "B", text: "对抗样本攻击" }, 
      { label: "C", text: "模型反演攻击" }, 
      { label: "D", text: "模型窃取攻击" }, 
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "304",
    questionText: "模型做出判断时高度依赖复杂的参数与非线性映射,使得其推理过程难以追溯,这种“____”现象妨碍了可解释性。",
    options: [
      { label: "A", text: "信息冗余" },
      { label: "B", text: "黑箱效应" },
      { label: "C", text: "神经激活偏差" },
      { label: "D", text: "局部最优陷阱" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "305",
    questionText: "(多选题)以下哪些情形属于对人工智能模型鲁棒性构成威胁?",
    options: [
      { label: "A", text: "模型对特定命令进行有害回复" },
      { label: "B", text: "模型难以识别对抗补丁遮挡的人体" },
      { label: "C", text: "模型在不同设备间运行速度不一致" },
      { label: "D", text: "模型对训练外情境无法做出正确反应" },
    ],
    correctAnswerLabel: "B, D", 
  },
  {
    id: "306",
    questionText: "可解释性风险不会导致模型输出错误结果,因此可以在高风险领域中忽略。",
    options: [
      { label: "A", text: "正确" },
      { label: "B", text: "错误" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "307",
    questionText: "为什么说“长尾风险”是鲁棒性问题的一种表现?",
    options: [
      { label: "A", text: "因为模型未能对训练集中大量出现的样本进行强化学习" },
      { label: "B", text: "因为模型在尾部少数情境下缺乏足够的训练经验" },
      { label: "C", text: "因为模型对数据中随机噪声过于敏感" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "308",
    questionText: "下列哪项攻击方式能在不知模型细节的前提下,通过接口构造出一个高度相似的模型?",
    options: [
      { label: "A", text: "模型蒸馏攻击" },
      { label: "B", text: "模型反演攻击" },
      { label: "C", text: "模型窃取攻击" },
      { label: "D", text: "成员推断攻击" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "309",
    questionText: "隐私性风险可能在训练、部署和使用各阶段发生,尤其当训练数据未经处理时更易泄露敏感信息。",
    options: [ 
      { label: "A", text: "正确" },
      { label: "B", text: "错误" },
    ],
    correctAnswerLabel: "A", 
  },
  {
    id: "310",
    questionText: "基于数据的AI风险防范技术不包括以下哪一项?",
    options: [
      { label: "A", text: "数据筛选与清洗" },
      { label: "B", text: "对抗训练" },
      { label: "C", text: "数据生成" },
      { label: "D", text: "数据增广" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "311",
    questionText: "以下哪项技术通过多个AI 智能体协作提升推理准确性?",
    options: [
      { label: "A", text: "模型自推理改进" },
      { label: "B", text: "多智能体推理" },
      { label: "C", text: "推理过程干预" },
      { label: "D", text: "数据增广" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "312",
    questionText: "数据清洗技术通过人工生成新样本解决数据稀缺问题,尤其在医疗领域应用广泛。",
    options: [
      { label: "A", text: "正确" },
      { label: "B", text: "错误" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "313",
    questionText: "检索增强生成技术依赖模型自身参数,不引入外部知识库。",
    options: [
      { label: "A", text: "正确" },
      { label: "B", text: "错误" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "314",
    questionText: "基于数据的 AI 风险防范技术中,以下哪项是提高已有数据质量的关键方式?",
    options: [
      { label: "A", text: "数据生成" },
      { label: "B", text: "数据增广" },
      { label: "C", text: "数据筛选与清洗" },
      { label: "D", text: "对抗训练" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "315",
    questionText: "(多选题)数据清洗的核心目标包括:",
    options: [
      { label: "A", text: "删除重复数据" },
      { label: "B", text: "修正标注错误" },
      { label: "C", text: "降低数据存储成本" },
      { label: "D", text: "去除异常数值" },
    ],
    correctAnswerLabel: "A, B, D", 
  },
  {
    id: "316",
    questionText: "(多选题)以下哪些属于基于训练策略的 AI 风险防范技术?",
    options: [
      { label: "A", text: "指令微调" },
      { label: "B", text: "检索增强生成" },
      { label: "C", text: "对抗训练" },
      { label: "D", text: "多智能体推理" },
    ],
    correctAnswerLabel: "A, C", 
  },
  {
    id: "317",
    questionText: "以下哪种风险防范技术能够实现模型的自我调节?",
    options: [
      { label: "A", text: "数据清洗" },
      { label: "B", text: "检索增强生成" },
      { label: "C", text: "多智能体推理" },
      { label: "D", text: "自我反思" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "318",
    questionText: "构建更完善的风险防范理论体系的核心任务不包括以下哪项?",
    options: [
      { label: "A", text: "制定统一的AI 价值体系" },
      { label: "B", text: "提升模型训练速度" },
      { label: "C", text: "分析安全防范的局限与制衡" },
      { label: "D", text: "发展系统化的安全优化理论" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "319",
    questionText: "从更完善的风险防范理论体系角度看,除了下列哪项外,都是需要采取的措施?",
    options: [
      { label: "A", text: "制定合理且统一的 AI 价值体系" },
      { label: "B", text: "发展更系统的安全优化理论" },
      { label: "C", text: "增加 AI 系统的计算能力" },
      { label: "D", text: "分析安全风险防范的局限与制衡" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "320",
    questionText: "超级对齐研究的目的是解决未来超级智能体可能超出人类控制的问题。这句话是否正确?",
    options: [
      { label: "A", text: "正确" },
      { label: "B", text: "错误" },
    ],
    correctAnswerLabel: "A",
  },
  {
    id: "321",
    questionText: "分析安全风险防范的“局限与制衡”时,需考虑____层面的因素。",
    options: [
      { label: "A", text: "仅技术" },
      { label: "B", text: "技术、伦理、法律" },
      { label: "C", text: "仅硬件性能" },
      { label: "D", text: "仅数据规模" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "322",
    questionText: "下列哪项不是建立更全面的多维度风险评测基准的作用?",
    options: [
      { label: "A", text: "掌握模型风险防范程度" },
      { label: "B", text: "发现模型风险的具体问题" },
      { label: "C", text: "解决模型推理速度不快的问题" },
      { label: "D", text: "进行公平性、有害性等性能的横向比较" },
    ],
    correctAnswerLabel: "C",
  },
  {
    id: "323",
    questionText: "下列哪项不属于更有效的风险防范治理应集中解决的问题?",
    options: [
      { label: "A", text: "AI 应用引发的社会与伦理问题" },
      { label: "B", text: "提升 AI 系统的计算能力" },
      { label: "C", text: "减轻 AI 对人类就业的负面影响" },
      { label: "D", text: "制定全面的治理战略" },
    ],
    correctAnswerLabel: "B",
  },
  {
    id: "324",
    questionText: "要打造有效的 AI 风险防范治理,需要哪些方面的协同合作?",
    options: [
      { label: "A", text: "政策制定者" },
      { label: "B", text: "企业领导者" },
      { label: "C", text: "研究人员" },
      { label: "D", text: "以上都是" },
    ],
    correctAnswerLabel: "D",
  },
  {
    id: "325",
    questionText: "AI风险防范治理的关键目标是?",
    options: [
      { label: "A", text: "优先保证模型计算效率" },
      { label: "B", text: "平衡技术创新与道德部署" },
      { label: "C", text: "减少模型参数量以降低成本" },
      { label: "D", text: "扩大 AI在军事领域的应用" },
    ],
    correctAnswerLabel: "B",
  }
];

export const MIN_QUESTIONS_SETUP = 5; // Minimum questions user can select for a quiz
export const MAX_QUESTIONS_PER_QUIZ_SETUP = 500; // Maximum questions user can select for a quiz
export const DEFAULT_NUM_QUESTIONS_SETUP = 10; // Default number of questions for a quiz
export const TOTAL_UNIQUE_QUESTIONS = ALL_QUESTIONS.length; // Total unique questions available in the bank
